### ISSUE TITLE
import WIP to headings template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#100]
Please import the WorkInProgress component into the HeadingsTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by Saurav50** [comment]
Hey Emma i want to work on this issue.
Thank You

**Comment by ctoffanin** [comment]
Yes, sure!
