### ISSUE TITLE
import WIP to icons template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#101]
Please import the WorkInProgress component into the IconsTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by Ashish-khanagwal** [comment]
Hello Emma,

Would love to work on this issue

Thank you

**Comment by ctoffanin** [comment]
Yes, sure, go ahead!

**Comment by Ashish-khanagwal** [comment]
Thank you for assigning it to me :)
