### ISSUE TITLE
Import WIP to Images template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#102]
Please import the WorkInProgress component into the ImagesTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by AbbeyIT** [comment]
Hi @EmmaDawsonDev I want to try to work on this issue

**Comment by EmmaDawsonDev** [comment]
Sure @AbbeyIT 😀
