### ISSUE TITLE
Import WIP to links template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#103]
Please import the WorkInProgress component into the LinksTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by DavidRod1865** [comment]
I'll like to work on this issue!

**Comment by ctoffanin** [comment]
Yes, sure!
