### ISSUE TITLE
Import WIP to lists template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#104]
Please import the WorkInProgress component into the ListsTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by Rohan-Hazari** [comment]
Hello can I try this issue?

**Comment by ctoffanin** [comment]
Yes, sure!
