### ISSUE TITLE
Import WIP to menus template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#105]
Please import the WorkInProgress component into the MenusTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by srishti2609** [comment]
I would like to work on this. Please assign it to me.

**Comment by EmmaDawsonDev** [comment]
Please go ahead 😊

**Comment by ctoffanin** [comment]
Hey @srishti2609, how is it going with the issue? Do you need any help?

**Comment by jyotika6221** [comment]
Hey, if there are no leads, can this issue be assigned to me?

**Comment by EmmaDawsonDev** [comment]
You can give it a go @jyotika6221

**Comment by Y0rubaCoproducer** [comment]
This looks like another good first issue for me! 
Thanks
Kemmy

**Comment by ctoffanin** [comment]
Hi @jyotika6221, how is it going with the issue? Do you need any help?

**Comment by thomasjvu** [comment]
Hello @EmmaDawsonDev and @ctoffanin 

I would love to contribute to this project as I admire the mission. Can I please be assigned to this issue?

I already have a solution ready! I just need to be assigned before I submit a PR per your contributing guidelines.

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead

**Comment by thomasjvu** [comment]
Thank you @EmmaDawsonDev!

I submitted the PR for review. I hope it's satisfactory.
