### ISSUE TITLE
Import WIP to modals template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#106]
Please import the WorkInProgress component into the ModalsTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by utkarsh1311** [comment]
I would like to work on this.

**Comment by EmmaDawsonDev** [comment]
Sure!
