### ISSUE TITLE
Import WIP to navigation template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#107]
Please import the WorkInProgress component into the NavigationTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by yashisahu** [comment]
Please assign me this issue

**Comment by ctoffanin** [comment]
Yes, sure, go ahead!

**Comment by ctoffanin** [comment]
Hey @yashisahu, how is it going with the issue? Do you need any help?

**Comment by jyotika6221** [comment]
Hey, if there are no leads, can this issue be assigned to me?

**Comment by EmmaDawsonDev** [comment]
Let’s give @yashisahu  a couple more days to answer then you can take over if there’s no response

**Comment by jyotika6221** [comment]
ok sure.

**Comment by ctoffanin** [comment]
@jyotika6221 are you still up for this?

**Comment by jyotika6221** [comment]
Thanks for assigning, can i get a brief about the task?

**Comment by EmmaDawsonDev** [comment]
> Thanks for assigning, can i get a brief about the task?

The brief is in the first message and it should be the same as the other issue you did last weekend. Any questions let us know.

**Comment by ctoffanin** [comment]
Hi @jyotika6221, how is it going with the issue? Do you need any help?

**Comment by yashisahu** [comment]
Yes..

**Comment by jyotika6221** [comment]
Hey,I got busy with another issue which hasn't been completed yet, would you mind assigning it to someone else. Sorry for the delay.

**Comment by ctoffanin** [comment]
No problem @jyotika6221. Thank you for your quick reply! @yashisahu are interested in this one?

**Comment by Huluvu424242** [comment]
Hello @ctoffanin, i have opened an PR #191 to fixing this issue. 
If you want, you can assign this issue to me or if other people (maybe @yashisahu) would like to work at this issue then assign to him - is no problem.
