### ISSUE TITLE
import WIP to pagination template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#108]
Please import the WorkInProgress component into the PaginationTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by iamshivi26** [comment]
I would like to work on this if this issue is still open.

**Comment by ctoffanin** [comment]
Yes sure
