### ISSUE TITLE
import WIP to tables template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#109]
Please import the WorkInProgress component into the TablesTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by EmmaDawsonDev** [comment]
Assigned to @huluvu424242

**Comment by Huluvu424242** [comment]
Thanks for assigning
