### ISSUE TITLE
Theme Switcher should close when tabbed out of

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#11]
**Describe the bug**
If someone is tabbing through the theme switcher, when it reaches the last item (dark) and someone continues to tab they end up on the navigation (home). When this happens the popup should automatically close.

**Comment by ctoffanin** [comment]
Hi, can I be assigned to this?

**Comment by EmmaDawsonDev** [comment]
Sure! Are you going to be taking part in hacktoberfest? If so feel free to wait until it starts before making the pr and I will add the hacktoberfest label to the repo.

**Comment by ctoffanin** [comment]
Mmm, I'm pretty new to everything. I'll join the hacktoberfest next year. Unless it's important to you as a maintainer, of course.

**Comment by EmmaDawsonDev** [comment]
No problem! Just wanted to check. If you need any help with anything just let me know 👍🏻

**Comment by EmmaDawsonDev** [comment]
Closed by #14
