### ISSUE TITLE
import WIP to video template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#110]
Please import the WorkInProgress component into the VideoTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by uddeshya-amit** [comment]
Is this issue still open ? I will like to work on it please assign it to me.

**Comment by EmmaDawsonDev** [comment]
Sure @uddeshya-amit
