### ISSUE TITLE
Adding actions on push, pull request 

### ISSUE THREAD

**Issue by ShubhraSuman** [AccessibleForAll/AccessibleWebDev#122]
**Is your feature request related to a problem? Please describe.**
It will be great if we can have GitHub actions whenever someone is pushing any code changes or raising a PR or automating build for every change.

**Describe the solution you'd like**
Implementation of workflows inside .GitHub will solve the purpose

**Comment by ShubhraSuman** [comment]
Can you assign this to me so that I can work on this issue.

**Comment by EmmaDawsonDev** [comment]
Can you be more specific about what kind of actions and what they will do?

**Comment by ShubhraSuman** [comment]
I was thinking to Create trigger whenever there is a code change or pull request. We can link it to main branch.

**Comment by EmmaDawsonDev** [comment]
What will the trigger do every time there is a code change/pull request?

**Comment by ShubhraSuman** [comment]
These all jobs:
It will check if job status.

name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

**Comment by EmmaDawsonDev** [comment]
I already have Gitpod installed which makes a workspace build  of every pull request so I don’t think this is needed too. Thanks for the suggestion though.
