### ISSUE TITLE
Update Pull Request Template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#130]
The pull request template in the .github folder has a checklist with 3 items. Add a fourth to the end of the list:

```- [ ] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave and it shows no errors```

**Comment by jyotika6221** [comment]
Please assign me this issue and describe in brief what should be the 4th item?

**Comment by Manujdixit** [comment]
@EmmaDawsonDev, assign this to me.

**Comment by Manujdixit** [comment]
@EmmaDawsonDev check the PR sent.

**Comment by EmmaDawsonDev** [comment]
the fourth item is this: `- [ ] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave and it shows no error`

**Comment by EmmaDawsonDev** [comment]
@jyotika6221 assigned

**Comment by jyotika6221** [comment]
thank you.

**Comment by jyotika6221** [comment]
Im done with the alloted task. Could you first accept my first pull request?
