### ISSUE TITLE
Update footer colors

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#132]
In `footer.module.css` the background color on line 2 should be changed as follows:

Current: `background-color: black;`

Change: `background-color: var(--dark);`

In `footer.module.css` the background color on line 34 should be changed as follows:

Current: `color: #00b4d8;`

Change: `color: var(--primary)`

**Comment by Manujdixit** [comment]
Hey @EmmaDawsonDev assign me this issue.

**Comment by jyotika6221** [comment]
Please assign me with this issue, this will be my first pr as i m a beginner i can start my journey with this. Thank you.

**Comment by ShubhamShakyawal** [comment]
@EmmaDawsonDev Please assign me. I would like to work on this

**Comment by EmmaDawsonDev** [comment]
Ah @Manujdixit got this one first.

**Comment by Manujdixit** [comment]
Thanks @EmmaDawsonDev

**Comment by jyotika6221** [comment]
hi emma , are there any more issues, i would like to contribute.
