### ISSUE TITLE
Update --dark variable color in global css

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#134]
In `globals.css` change row 9 and row 20

Current: `--dark: #000;`

Change: `--dark: #1c1c1c;`

**Comment by ShubhamShakyawal** [comment]
@EmmaDawsonDev Please assign me. I would to work on this

**Comment by mnkyjs** [comment]
Hey @EmmaDawsonDev it would be a pleasure to do this 😊

**Comment by EmmaDawsonDev** [comment]
@ShubhamShakyawal you are assigned :)

**Comment by ShubhamShakyawal** [comment]
@EmmaDawsonDev Successfully made changes and created Pull Request
https://github.com/AccessibleForAll/AccessibleWebDev/pull/135
