### ISSUE TITLE
Add About page

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#139]
In the pages folder add an about.tsx page.

Include a head and a layout (see index.tsx for guidance) As there is no contents currently the Work in progress component can be imported and used as a placeholder.

The title of the page should be About - Accessible Web Dev
headerTitle should be About Us
activeNavLink can be an empty string for now (I don't want this page to be part of the main navigation)

**Comment by sculley** [comment]
Howdy, I would like to work on this issue. Can you assign it to me please?

**Comment by jyotika6221** [comment]
Please assign me this issue.

**Comment by ctoffanin** [comment]
@sculley was first.

**Comment by jyotika6221** [comment]
ok, are there any more issues?

**Comment by EmmaDawsonDev** [comment]
> ok, are there any more issues?

I'm sure there will be later :)

**Comment by jyotika6221** [comment]
ok thank you, shall wait.
