### ISSUE TITLE
update casing on name of footer.module.css

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#148]
1. Rename `footer.module.css` to `Footer.module.css`
2. Update the import on line 3 in Footer.tsx to `import styles from "./Footer.module.css"`

**Comment by vavy06** [comment]
Hi! Could you please assign the task to me?

**Comment by Devesh-coder** [comment]
Hey @EmmaDawsonDev I would love to contribute to this issue!

**Comment by EmmaDawsonDev** [comment]
@vavy06 got this one :)
