### ISSUE TITLE
Gitpodify the repo

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#15]
Add a .gitpod.yml file to the root of the repository.

The contents of the file should be similar to the one here https://github.com/EddieHubCommunity/LinkFree/blob/main/.gitpod.yml but npm should be switched for yarn

**Comment by Nikhil-1503** [comment]
Hey Emma,
Can I work on this as well?

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead :)
