### ISSUE TITLE
Update pull request template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#157]
The pull request template currently has the following headings:

```
## Issue ticket number and link - If Any

## Checklist before requesting a review
```

Update to 
```
## Link to issue
<!-- Example: Closes #31 -->
Closes #

## Checklist before requesting a review
```

**Comment by FaithKovi** [comment]
Hi @EmmaDawsonDev I want to work on this issue
Please assign

**Comment by EmmaDawsonDev** [comment]
Sure! It's in the .github folder called PULL_REQUEST_TEMPLATE.md

**Comment by FaithKovi** [comment]
Hello, @EmmaDawsonDev I have completed this task and created a pull request.
