### ISSUE TITLE
Add an description for the table section

### ISSUE THREAD

**Issue by Huluvu424242** [AccessibleForAll/AccessibleWebDev#159]
**Is your feature request related to a problem? Please describe.**
The table area has no content.

**Describe the solution you'd like**
Add example code snippets and describe the rules. You should take the content from this page:
https://www.w3.org/WAI/tutorials/tables/caption-summary/

**Describe alternatives you've considered**
There are many alternative pages at the internet for a11y. You can use from other site but you must check the copyright.

**Additional context**
If you use content from this url, i think you must copy all content to meet the copyright rules. 
see here: https://www.w3.org/WAI/about/using-wai-material/

and you must add an link to the source 

and maybe you must add the copyright notice:
Copyright © 2022 W3C ® ([MIT](https://www.csail.mit.edu/), [ERCIM](https://www.ercim.eu/), [Keio](https://www.keio.ac.jp/), [Beihang](https://ev.buaa.edu.cn/)) [Permission to Use WAI Material](https://www.w3.org/WAI/about/using-wai-material/).

**Comment by EmmaDawsonDev** [comment]
Hi @Huluvu424242 none of the sections currently have any content but adding content is the next stage of the project. We will start by adding one page at a time so the tables page may take a while. However, we will not be copying anything directly from any other websites. Thanks for the link though, I’m sure we can add it to the list of references if we find it useful.

**Comment by Huluvu424242** [comment]
My original idea was not to copy but then i found this site and i remember the facts of my personal experience:

1. It is very difficult to write an general tutorial to realize a11y. Most cases are depends of domain. 2 people has most 3 solutions ;)
2. The source of content was important for me, because it is the world wide standard organization for this - i think so. 
3. The rules of copyright at this page seems to force to copy.

So i am happy to read you have an own solution for this problem. I am excited and happy look forward. 

Sorry for my bad english - if you dont understand it - here is my original language:
Ich freue mich darüber, dass Sie eine eigene Lösung zum Füllen der Seiten mit Inhalt haben. Denn ich hatte befürchtet Sie würden nach besten Wissen Stückchen der "Besten Vorgehensweisen" aus dem Internet  suchen und hier zusammen bringen. 

Meine Erfahrung auf dem Gebiet zeigte mir, dass es sehr schwierig ist eine Anleitung zur Erstellung barrierefreier Seiten bereitzustellen. Meist sind die Lösungen von der fachlichen Domäne (subject domain) abhängig und wenn 2 Personen diese diskutieren finden sie mindestens 3 Lösungen :) 

Daher war ich sehr froh, dass die W3C eine Art Anleitung bereitstellt, da diese Organisation für mich praktisch die Schirmherrschaft für den weltweiten Standard dieser Thematik darstellt. Die Urheberregeln der Seiten auf w3.org interpretierte ich dann aber so, dass man wenn man etwas kopiert alles kopieren muss und da ein einfaches Tabellen Beispiel vermutlich immer gleich aussieht, sehe ich darin ein Problem. 

Von daher freut es mich zu lesen, dass Sie sich von vornherein Gedanken über die Bereitstellung  der Inhalte gemacht haben und es nicht dem Zufall und dem Glück des Hacktoberfestes und der Contributoren überlassen. 

Ich bin gespannt auf Ihre Lösung und schaue zuversichtlich in die Zukunft :)

Happy Hacktoberfest

**Comment by EmmaDawsonDev** [comment]
Ah, thanks so much for explaining! 

The hacktoberfest contributions are helping me to get the website template in place but not to worry, I'm planning on writing a lot of the content myself and any contributions will be checked and verified for accuracy and understanding before being merged. Spreading wrong information is something I definitely want to avoid!

**Comment by YuriDevAT** [comment]
Hey @Huluvu424242.

Vielen Dank für dein Kommentar. Wir verstehen deine Bedenken sehr gut, kann dir aber versichern, dass Emma, und der Rest des Teams großen Wert auf Richtigkeit und Genauigkeit legen, und jeder PR genauestens geprüft wird. Wenn du weitere Fagen haben solltest, und diese lieber auf Deutsch kommunizierst, kannst du mir gerne taggen 🙂

**Comment by ctoffanin** [comment]
Thank you @YuriDevAT!

**Comment by EmmaDawsonDev** [comment]
Thanks so much Julia!
