### ISSUE TITLE
Add Skiplink

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#16]
Add a skiplink button component. 

[] It should be a html a element
[] It should be imported into the layout component and placed before the header. 
[] It should be hidden offscreen a few pixels above where it will normally be positioned but appear in the center of the header when tabbed to. Maybe a small transition could be added so it slides into place?
[] It should be styled to have black text, white background and a pink border (like a button).
[] It should move focus to the main element (also inside layout) when pressed - add an id to the main tag to do this.
[] Text should be: Skip to main content

**Comment by ctoffanin** [comment]
Hi Emma, I really suck at CSS, this could be a good one to do little practice.
Can I be assigned to this as well?

**Comment by EmmaDawsonDev** [comment]
Sure, feel free to give it a go and let me know if you need any help.

**Comment by ctoffanin** [comment]
Hi Emma, is this what you were expecting to see?

https://user-images.githubusercontent.com/1682188/192809717-ddb184e4-1a20-49d2-894e-52c100e9b08f.mov

**Comment by EmmaDawsonDev** [comment]
Yes! That’s pretty much what I envisioned 😀
