### ISSUE TITLE
Theme change

### ISSUE THREAD

**Issue by LucasWongC** [AccessibleForAll/AccessibleWebDev#160]
I am not sure what Device Settings is for in theme change on the right top.
I think something like toggle button is enough for changing theme.

**Comment by ctoffanin** [comment]
Device Settings makes sense for users that set to auto the light/dark theme on their devices. 
The theme then goes dark automatically at sunset and light from the sunrise.
In this way, the website theme will also adjust based on that setting.

**Comment by EmmaDawsonDev** [comment]
Thanks for raising the issue @LucasWongC As Cristian explained, it's there to follow system settings but light and dark modes will override any system settings in case you don't like the color modes provided. However, if you don't think it's clear what it does I'd be interested to know if you have a suggestion for a clearer label.

**Comment by LucasWongC** [comment]
Thanks for your reply.
And I'd like to join this community.

**Comment by ctoffanin** [comment]
@LucasWongC to join the community, you only need to open an issue here: https://github.com/AccessibleForAll/Support
