### ISSUE TITLE
Add Footer story

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#165]
The Footer component already exists but there's no story for it in storybook.

In the `stories` folder add a file named `Footer.stories.tsx`

Using the `Header.stories.tsx` file as a template, adapt the contents of that file for the Footer component.

The Footer component takes no props.

Use the command `yarn storybook` to run the story on localhost and check that component is visible in storybook.

**Comment by murtuzaalisurti** [comment]
this seems interesting as I have never used storybook, can I work on this?

**Comment by ctoffanin** [comment]
Hi, sure. Go ahead. Let us know if you need any help.
