### ISSUE TITLE
Add NavPrimary story

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#166]
The NavPrimary component already exists but there's no story for it in storybook.

In the `stories` folder add a file named `NavPrimary.stories.tsx`

Using the `Header.stories.tsx` file as a template, adapt the contents of that file for the NavPrimary component.

The NavPrimary component takes activeNavLink (a string) as props. It can be set as "home" in the story args.

Use the command `yarn storybook` to run the story on localhost and check that component is visible in storybook.

**Comment by MarkusEicher** [comment]
Hi Emma. May I kindly ask you to assign this to me? Thank you!

**Comment by ctoffanin** [comment]
Yes, go ahead!

**Comment by MarkusEicher** [comment]
Hi there. Just a ping that I'm still working on the issue. First try was a fail. The story didn't appear as expected.

**Comment by ctoffanin** [comment]
No worries, take your time. Let us know if you need any help!

**Comment by MarkusEicher** [comment]
Thanks a lot for the support. Appreciate it. At this point I need to dig into it again. Will do that later this day. If it still won't work, I will be glad to reach out to you or have the issue reassigned to another contributor.

**Comment by hariscs** [comment]
hi @MarkusEicher, you still working on this? if you need any help leave the query here or if you want to unassign it, I would be happy to work on this.

**Comment by EmmaDawsonDev** [comment]
@MarkusEicher please take all the time you need to work on your issues, they are non-critical so there is no rush. I see other people asking to be assigned but I don’t want you to feel pressured to give up an issue just because someone else asks for it.

**Comment by MarkusEicher** [comment]
@EmmaDawsonDev Thank you, Emma. I really appreciate this! 💚 If I need help I will reach out and it will not take a lot longer. I have freed some time for it.

**Comment by hariscs** [comment]
hey @MarkusEicher, sorry if you felt pressured by my last comment. take your time and I'm going to share some resources with you where you can learn storybook and react typescript. and if you need any help leave your comment here, I would love to help you with this.
you can learn storybook from [here](https://www.youtube.com/watch?v=qSkHRVLcj6U&ab_channel=MariusEspejo)

**Comment by MarkusEicher** [comment]
Thanks @hariscs. 👊 Didn't feel pressured at all. I appreciate your offer to support me. I'm just about to add my solution. Will be glad to reach out if I need help. Have a good day 🍀

**Comment by MarkusEicher** [comment]
Hello community. I just started to finalize this issue. Just to let you know that it's still work in progress. Have a good day.
