### ISSUE TITLE
Add NavPrimaryMobile story

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#167]
The NavPrimaryMobile component already exists but there's no story for it in storybook.

In the stories folder add a file named NavPrimaryMobile.stories.tsx

Using the Header.stories.tsx file as a template, adapt the contents of that file for the NavPrimaryMobile component.

The NavPrimaryMobile component takes activeNavLink (a string) and a handleClick (function) as props. activeNavLink can be set as "home" in the story args.

Use the command yarn storybook to run the story on localhost and check that component is visible in storybook.

**Comment by hariscs** [comment]
Hey @EmmaDawsonDev assign this to me, I wanna work on it

**Comment by ctoffanin** [comment]
Hi, sure. Go ahead. Let us know if you need any help.
