### ISSUE TITLE
Add NavItem story

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#168]
The NavItem component already exists but there's no story for it in storybook.

In the stories folder add a file named NavItem.stories.tsx

Using the Header.stories.tsx file as a template, adapt the contents of that file for the NavItem component.

The NavItem component takes the following props:
```
interface NavItemProps {
	page: IPage
	activeNavLink: string
	handleNavClick?: () => void
}
```

Use the command yarn storybook to run the story on localhost and check that component is visible in storybook.

**Comment by Huluvu424242** [comment]
Hello, please assign to me. 

Do you have an example for the handleNavClick function?

**Comment by EmmaDawsonDev** [comment]
Sure! The handleNavClick function looks like this:

```
const [showNavMobile, setShowNavMobile] = useState<boolean>(false)

	const handleNavClick = () => {
		setShowNavMobile((prevState) => !prevState)
	}

```

and is sent through props from a parent component

**Comment by EmmaDawsonDev** [comment]
Although it is not required and in this case of only rendering the nav item it probably doesn't make sense to include it.

**Comment by Huluvu424242** [comment]
This PR is not valid at now. At the moment i need an hint to solve the problem.
