### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#17]
The project is currently using the default next favicon. Either it can be switched out for the AccessibleForAll icon on github or if you wish to design one that is in line with the project feel free to have a go at that.

**Comment by Nakamcode** [comment]
I want to work on this.

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead!

**Comment by EmmaDawsonDev** [comment]
> Please send me the image of the logo 

I don't have access to my laptop for a couple of days but I'll send it at the weekend. Please remind me on Saturday if I forget.

**Comment by Nakamcode** [comment]
Alright

**Comment by EmmaDawsonDev** [comment]
![AFA logo](https://user-images.githubusercontent.com/57045550/193401831-4249b3ba-c951-4757-bf9c-877c3463b9ac.png)

**Comment by Nakamcode** [comment]
Thank you
