### ISSUE TITLE
Create MaintainerCard component (and story)

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#170]
If you don't feel comfortable with using storybook to create the component feel free to ignore the storybook steps and they can be added later.

In the `components` folder create a folder called `MaintainerCard`. Inside the folder create a component called `MaintainerCard.tsx` and a CSS file called `MaintainerCard.module.css`

In the `stories` folder create a file called `MaintainerCard.stories.tsx`

The `Header.stories.tsx` can be used for guidance of how to set up the story for the Maintainer Card story. 

To run storybook and see changes to the component use the command `yarn storybook`

Create the Maintainer Card component following this design:
<img width="150" alt="image" src="https://user-images.githubusercontent.com/57045550/196050804-64c5280a-c0c7-4576-9eaf-b85b06f42987.png">

Everything can be hardcoded as a placeholder to begin with.

**Comment by Gammarkin** [comment]
I would like to contribute. Can you assign this issue to me?

**Comment by ctoffanin** [comment]
Hi, yes, sure, go ahead!
