### ISSUE TITLE
Add a11y-addon to storybook

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#171]
Follow the instructions at [Storybook - set up ally addon](https://storybook.js.org/docs/react/writing-tests/accessibility-testing#accessibility-checks-with-a11y-addon) in order to install and configure the accessibility add on. (Only this section needs to be followed, no need to add anything in the configure section)

Please use yarn to install the new package and follow the Typescript instructions for configuration.

**Comment by YuriDevAT** [comment]
Hey @EmmaDawsonDev. I would love to work on this issue 🙂

**Comment by ctoffanin** [comment]
Hey @YuriDevAT, sure! Please go ahead! 😄

**Comment by YuriDevAT** [comment]
Perfect, thanks.
