### ISSUE TITLE
incorrect text formatting

### ISSUE THREAD

**Issue by murtuzaalisurti** [AccessibleForAll/AccessibleWebDev#175]
**Describe the bug**
Missing space in footer text

**Screenshots**
![chrome_rIHFcQoxLc](https://user-images.githubusercontent.com/68743212/196492986-c93ffff8-97b9-40df-b435-25361c2d1190.jpg)

**Comment by EmmaDawsonDev** [comment]
Thanks for noticing! Would you like to be assigned?

**Comment by murtuzaalisurti** [comment]
yeah why not

**Comment by murtuzaalisurti** [comment]
made a PR
