### ISSUE TITLE
[Fix] Aligning the footer's content

### ISSUE THREAD

**Issue by digambar-t7** [AccessibleForAll/AccessibleWebDev#178]
**Describe the bug**
I think the content placed in the footer space is misaligned.Was it made intentionally?

**To Reproduce**
1. Come to the bottom of the home page
2. Observe the content in the footer space(bg black)

**Expected behavior**
The content should have been properly aligned around the vertical axis unless it wasn't meant to be the way it is now.

**Screenshots**
![Screenshot from 2022-10-19 00-44-02](https://user-images.githubusercontent.com/92970968/196523910-e3d43231-98c2-444d-8aa0-a3f67b29cdb0.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 104.0.5112.79

**Comment by EmmaDawsonDev** [comment]
Yes, it is misaligned. The edges should be aligned with the hr element above it. Is it something you'd like to fix?

**Comment by digambar-t7** [comment]
Yes @EmmaDawsonDev I'd like to fix it

**Comment by ctoffanin** [comment]
Go ahead @digambar-t7!

**Comment by digambar-t7** [comment]
![Screenshot_2022-10-21_23_26_11](https://user-images.githubusercontent.com/92970968/197259868-e0bc17f9-b6ad-4ff8-9dae-f3c0a1f4eece.png)





> Yes, it is misaligned. The edges should be aligned with the hr element above it. Is it something you'd like to fix?

Hey @EmmaDawsonDev,  were you suggesting this ?

**Comment by EmmaDawsonDev** [comment]
Yes, that's exactly what I was thinking 👍

**Comment by digambar-t7** [comment]
Ok, then I'll raise a PR shortly.
