### ISSUE TITLE
Dockerize the app

### ISSUE THREAD

**Issue by Pradumnasaraf** [AccessibleForAll/AccessibleWebDev#179]
**Is your feature request related to a problem? Please describe.**
Adding Docker support to the repo by adding `Dockerfile` and `compose` for the dev who works in a container environment.

**Comment by hariscs** [comment]
quick question, @Pradumnasaraf what are the benefits of dockerizing this app?

**Comment by Pradumnasaraf** [comment]
> quick question, @Pradumnasaraf what are the benefits of dockerizing this app?

Many people do local development in containerized environments. So will be easy for them to contribute.

**Comment by EmmaDawsonDev** [comment]
Thanks for the suggestion Pradumna. I'm not really sure of the benefit of this right now. I don't want to make it more complex than it needs to be.

**Comment by Pradumnasaraf** [comment]
Thanks for reply Emma. 

It doesn't make the App complex (Nothing need to change on itself, It's a separate `Dockerfile`) 😅, even it's make easy to contribute and testing.

Closing the issue.
