### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#18]
Add a 404.tsx file to the pages folder. Wrap the contents with the layout (see other pages for an example). Then write a 404 message eg. Oops, that page doesn't exist! and add a link back to the homepage.

**Comment by yashfalke77** [comment]
@EmmaDawsonDev  can I work on this issue

**Comment by EmmaDawsonDev** [comment]
Sure! If you're joining hacktoberfest then feel free to wait until October before making a pull request.

**Comment by yashfalke77** [comment]
Yes, I am joining hacktoberfest, but I had  one doubt @EmmaDawsonDev , will it be okay if I forked now and completed the above task and then after registering for  hacktoberfest and then I will request for pull request. Will it be okay? actually i am new to theopen source contribution so i don't have much idea

**Comment by EmmaDawsonDev** [comment]
Hi @yashfalke77 yes, that's perfectly fine. I do the same thing :) You can fork it now and work on it this week. Just wait until October 1st before making the PR.

**Comment by yashfalke77** [comment]
Hi @EmmaDawsonDev I completed the 404 page designing below are the screenshots both in light and dark mode, if there are any changes then please tell me

Dark mode: 
![image](https://user-images.githubusercontent.com/82655175/192759075-0534386b-9136-4729-a26b-e69fd1847b3a.png)

Light mode:
![image](https://user-images.githubusercontent.com/82655175/192759260-71d98d9b-be8b-4b24-a4bf-db8f5189e7a3.png)

**Comment by EmmaDawsonDev** [comment]
Looks great! Where’s the image from? Just want to check whether the image is royalty free so we can use it without needing to give credit. Also, there’s a small spelling mistake on captcha

**Comment by yashfalke77** [comment]
@EmmaDawsonDev Image is of royalty free from [error404](https://error404.fun/) website ,  i will correct it , rest all okay? . Is ready for pull requests?

**Comment by EmmaDawsonDev** [comment]
Cool, I’ve not seen that site before 👍🏻 All looks ok I think, now just to wait until the weekend to make your PR 😀

**Comment by yashfalke77** [comment]
hey @EmmaDawsonDev I made the pull request do check it out and if everything is okay you can merge it :)
