### ISSUE TITLE
Dark mode flickering

### ISSUE THREAD

**Issue by Olaleye-Blessing** [AccessibleForAll/AccessibleWebDev#182]
**Describe the bug**
A white background showed for some seconds after switching to dark mode and reloading the page.

**To Reproduce**
1. Go to [website](https://accessiblewebdev.netlify.app/)
2. Switch the theme to the dark mode
3. Reload the page
4. Notice the bug

**Expected behavior**
The white background shouldn't show at all. That is, the flickering shouldn't happen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Browser [e.g. brave]
 - Version [e.g. 10]

**Smartphone (please complete the following information):**
 -

**Additional context**
-

**Comment by EmmaDawsonDev** [comment]
Nicely spotted. My guess is that this has something to do with the server-side rendering of the page always in lightmode which causes a brief flash before the user's systems settings can kick in and change to dark mode on the client side.

**Comment by Olaleye-Blessing** [comment]
Yeah, I'll like to work on it.

**Comment by ctoffanin** [comment]
Yes, sure, go ahead.
