### ISSUE TITLE
PRs not accepted in hacktoberfest

### ISSUE THREAD

**Issue by hariscs** [AccessibleForAll/AccessibleWebDev#186]
**Describe the bug**
hey, @ctoffanin @EmmaDawsonDev i created two PRs, and both of them got merged in this project but none of them are accepted in the hacktoberfest.

**Screenshots**
![image](https://user-images.githubusercontent.com/60646718/197949675-251db12c-b30e-4f94-bfe4-6443330753f5.png)

**Comment by EmmaDawsonDev** [comment]
Try doing a hard refresh of the hacktoberfest page, it’s probably a caching issue
