### ISSUE TITLE
Add maintainer cards to about page

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#189]
In `about.tsx` remove the WorkInProgress component and replace it with an h2 that says Current Maintainers. 

Import the MaintainerCard into the file and remove the WorkInProgress import.

Directly beneath the h2 map over the maintainerData and pass each object into the maintainerCard component.

Verify that 2 cards show on the screen with names, descriptions and github links (images will be added later).

This issue is for @sano2019

**Comment by itzwow** [comment]
Hey can I work on this issue?

**Comment by EmmaDawsonDev** [comment]
@itzwow sorry, this issue is already assigned to @sano2019.

**Comment by sano2019** [comment]
Thanks Emma. I’ll work on it tomorrow

**Comment by itzwow** [comment]
> @itzwow sorry, this issue is already assigned to @sano2019.

Alright No problem . : )
