### ISSUE TITLE
Add a footer

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#19]
Create a footer component that can be imported into the layout component.

The Footer should have the same background and text colors as the header.

Add a link to the the github repository https://github.com/AccessibleForAll/AccessibleWebDev

**Comment by yashfalke77** [comment]
@EmmaDawsonDev can I work on this issue to?

**Comment by EmmaDawsonDev** [comment]
Sure!

**Comment by yashfalke77** [comment]
hey @EmmaDawsonDev  completed the footer below is the screenshot of it if any changes needed do tag me :)

![image](https://user-images.githubusercontent.com/82655175/193315527-97d989f6-b767-4cea-91fe-3e4427718cb5.png)

**Comment by EmmaDawsonDev** [comment]
I love the design of it 👍 but maybe it includes too many links for the time being.

Above the line could we just have the Community section for now? And remove the 'give us a coffee' and replace with 'Sponsor us' as I can set up github sponsorships.

Below the line I love the tagline you've written and github icon is great. We don't have a linked in currently or any other socials so that one can be removed.

**Comment by yashdev9274** [comment]
Is @yashfalke77  still working on it?

**Comment by yashfalke77** [comment]
@yashdev9274 yes

**Comment by yashfalke77** [comment]
Hey @EmmaDawsonDev from design perspective we should have at least two section one I will keep community and second will be tools will it be okay?

**Comment by EmmaDawsonDev** [comment]
@yashfalke77 then maybe it is best to keep the community and company sections instead. I’m not keep on dividing up the pages like that and many other pages are being added currently so it might be weird to only have links to some of them. Let’s start with community and company.

**Comment by yashfalke77** [comment]
@EmmaDawsonDev ok sure :)

**Comment by yashfalke77** [comment]
Hey @EmmaDawsonDev  made the changes according to you , if any further changes needed do tag me 
![image](https://user-images.githubusercontent.com/82655175/193418538-3fef43a0-d705-4b9a-9f72-b9e43ac2b1ab.png)

**Comment by EmmaDawsonDev** [comment]
Looks great! If you go ahead and make a pull request then I can review the code and see if anything else needs changing.
