### ISSUE TITLE
MaintainerCard component has wrong margin

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#192]
**Describe the bug**
In the file `MaintainerCard.module.css`  the margin on class `.maintainerContainer` is currently set at `4.5rem` all the way round. This should be changed to `4.5rem 0 0 0`

**Comment by goobric** [comment]
hi Emma, can I please be assigned this issue?

**Comment by aditya-rastogi23** [comment]
hi @EmmaDawsonDev does this work?

**Comment by EmmaDawsonDev** [comment]
Please wait to be assigned an issue as stated in the contributing guidelines before making a pull request in the future, otherwise your PR may be closed.

**Comment by EmmaDawsonDev** [comment]
Now I see that @goobric actually asked to be assigned so they will get the chance first

**Comment by aditya-rastogi23** [comment]
I'm really sorry about it. Can this one still be merged? I'm relatively new to open source and am trying to dig deeper

**Comment by goobric** [comment]
Hi Emma,
I created a new branch (MaintainCard) altered the margin value within the MaintainerCard section, and sent a Pull Request.
Thank you so much for giving me this opportunity to participate and practice.
