### ISSUE TITLE
About page layout needs fixing on mobile

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#193]
In the file `about.module.css` add the following to the `.aboutRow` class:
```
flex-wrap: wrap;
gap: 1rem;
```

Check that the maintainer cards then wrap into one column on mobile.

**Comment by goobric** [comment]
hi Emma, can I please be assigned this issue?

**Comment by EmmaDawsonDev** [comment]
Of course!

**Comment by goobric** [comment]
Hi Emma,
thank you so much for giving me the chance to practice -> forking, branching, updating, & sending a PR

**Comment by EmmaDawsonDev** [comment]
You’re more than welcome! Thanks so much for contributing 😀
