### ISSUE TITLE
Add gitpod badge to readme

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#20]
Please add the following code snippet to the bottom of the readme file 

```[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev)```

**Comment by Ashish-khanagwal** [comment]
Hey Emma, I would love to work on this issue. Assign it to me

**Comment by EmmaDawsonDev** [comment]
Sure!

**Comment by Ashish-khanagwal** [comment]
Thank you

**Comment by Ashish-khanagwal** [comment]
as @MrKrishnaAgarwal already resolved this issue. So, I don't have to create a PR now.

**Comment by MrKrishnaAgarwal** [comment]
> as @MrKrishnaAgarwal already resolved this issue. So, I don't have to create a PR now.

Yes, I have resolved #20 and #15 both

**Comment by EmmaDawsonDev** [comment]
@Ashish-khanagwal since you are assigned to this issue I will merge your pull request over someone else’s as I don’t feel it’s good etiquette that people take assigned issues from others, especially during hacktoberfest. So please go ahead and make your PR.

**Comment by MrKrishnaAgarwal** [comment]
> @Ashish-khanagwal since you are assigned to this issue I will merge your pull request over someone else’s as I don’t feel it’s good etiquette that people take assigned issues from others, especially during hacktoberfest. So please go ahead and make your PR.

Should I close my PR then?

**Comment by EmmaDawsonDev** [comment]
> > @Ashish-khanagwal since you are assigned to this issue I will merge your pull request over someone else’s as I don’t feel it’s good etiquette that people take assigned issues from others, especially during hacktoberfest. So please go ahead and make your PR.
> 
> Should I close my PR then?

Yes, please only makePRs for issues you are assigned to. If you see an issue that’s already assigned but seems abandoned after a couple of weeks feel free to ask about having it reassigned. I’m also hoping to add more issues later this weekend

**Comment by MrKrishnaAgarwal** [comment]
> > > @Ashish-khanagwal since you are assigned to this issue I will merge your pull request over someone else’s as I don’t feel it’s good etiquette that people take assigned issues from others, especially during hacktoberfest. So please go ahead and make your PR.
> > 
> > 
> > Should I close my PR then?
> 
> Yes, please only make PRs for issues you are assigned to. If you see an issue that’s already assigned but seems abandoned after a couple of weeks feel free to ask about having it reassigned. I’m also hoping to add more issues later this weekend

yes sure, please add them

**Comment by Ashish-khanagwal** [comment]
okay, then I'll make PR on this issue
