### ISSUE TITLE
Add a scrollbar to the menu

### ISSUE THREAD

**Issue by tinniaru3005** [AccessibleForAll/AccessibleWebDev#200]
**Is your feature request related to a problem? Please describe.**
A scroll bar can be added

**Describe the solution you'd like**
Add a scrollbar here
![add scrollbar](https://user-images.githubusercontent.com/62856848/198840412-e02f9abd-09b0-4318-8d02-49c07c11d80f.png)

The scrollbar can be similar to:
![scrollbar](https://user-images.githubusercontent.com/62856848/198840441-cb1173f2-e4e5-4eb1-b9f1-2bd6877957de.png)

**Comment by tinniaru3005** [comment]
Can you please assign me the issue, I would like to work on it.

**Comment by EmmaDawsonDev** [comment]
At the moment the sidebar probably looks weird as there's no content but eventually when content is added then there will be no need for a scrollbar.
