### ISSUE TITLE
Add PaginationTemplate component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#21]
In the components/templates folder add a PaginationTemplate.tsx file. Copy the structure of one of the other templates (they're all currently the same apart from name - contents will be added later). Update the component name so it matches the file name.

In the pages/[content].tsx file import the template and add it alphabetically in the correct place between the layout tags

Add the template data to the config file in data/pages.tsx

**Comment by Giriraj-Roy** [comment]
Hello ma'am,
I have gone through the repository and the given instructions. The issue seems to attract my interest and excites me to work on it. I humbly wait for you to assign the task to me if your analysis of my profile allows.

Yours Sincerely,
Giriraj Roy.

**Comment by ahmedsilat44** [comment]
Hey @EmmaDawsonDev I am new to open source and I would like to do this task. Could you please assign me to this task. 
Thanks 😄

**Comment by EmmaDawsonDev** [comment]
Sure! If you're taking part in hacktoberfest just wait until October 1st to make the PR.

**Comment by ahmedsilat44** [comment]
Ok. Thanks for the heads up. Its my first time taking part in hacktoberfest.

**Comment by ahmedsilat44** [comment]
@EmmaDawsonDev Hey while trying to commit to my branch I ran into an error.
![image](https://user-images.githubusercontent.com/105588821/192586244-07012e04-d269-4712-90ce-3d245e161cc9.png)
Could you please tell me how to fix this

**Comment by EmmaDawsonDev** [comment]
@ahmedsilat44 did you solve the issue you were having with committing? I can’t see the screenshot you posted anymore 🤔 if not, I suggest trying to commit via the terminal and let me know if it doesn’t work

**Comment by ahmedsilat44** [comment]
@EmmaDawsonDev Yes I solved the issue. I kept having the error while commiting through Github Desktop but after 2 hours of struggling to find the solution I used the terminal and it worked. Thanks for the reply 👍
