### ISSUE TITLE
Add NavigationTemplate component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#22]
In the components/templates folder add a NavigationTemplate.tsx file. Copy the structure of one of the other templates (they're all currently the same apart from name - contents will be added later). Update the component name so it matches the file name.

In the pages/[content].tsx file import the template and add it alphabetically in the correct place between the layout tags ```{page === "navigation" && <Navigation />}```

Add the template data to the config file in data/pages.tsx: ```{ name: "Navigation", href: "/navigation", content: "navigation" }```

**Comment by krupalitrivedi** [comment]
Hello Emma!

I would love to work on this one! :)

Thank you!

**Comment by EmmaDawsonDev** [comment]
Sure!
