### ISSUE TITLE
Consistent Props importing

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#229]
Currently the props are being imported in two different ways:
Style 1:
```
export const Header = (props: HeaderProps) => {
	const { headerTitle, handleNavClick, showNavMobile } = props
```

and 

Style 2:
```
export const CodeBlock = ({ codeSnippet }: ICodeBlockProps) => {
```

Please go through all the components and change the ones using style 1 to use style 2 instead so it should look like this in every component:
```
export const Header = ( { headerTitle, handleNavClick, showNavMobile }: HeaderProps) => {
```

**Comment by hariscs** [comment]
assign it to me

**Comment by EmmaDawsonDev** [comment]
Assigned. Let us know if you need any help with anything

**Comment by mohit1607** [comment]
I am also up for this task.   Pleasse assign it to me also

**Comment by hariscs** [comment]
Hey @mohit1607, great to see you are taking interest in this project but I already worked on this issue.
This is an active project @EmmaDawsonDev will be adding more issues maybe you can work on that.
