### ISSUE TITLE
Add MenusTemplate component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#23]
In the components/templates folder add a MenusTemplate.tsx file. Copy the structure of one of the other templates (they're all currently the same apart from name - contents will be added later). Update the component name so it matches the file name.

In the pages/[content].tsx file import the template and add it alphabetically in the correct place between the layout tags ```{page === "menus" && <Menus />}```

Add the template data to the config file in data/pages.tsx: ```{ name: "Menus", href: "/menus", content: "menus" }```

**Comment by Ashish-khanagwal** [comment]
Hello Emma,
 
Would love to work on this issue

Thank you

**Comment by EmmaDawsonDev** [comment]
Of course 👍🏻

**Comment by Ashish-khanagwal** [comment]
Thank you
