### ISSUE TITLE
Named exports

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#230]
We have decided that all components will use named exports. However, at the moment some are still using export default.

Please go through the components (not pages) and update each to use named exports.

Example: 
```
const AlertsTemplate = () => {
	return <WorkInProgress />
}

export default AlertsTemplate
```

Should become:
```
export const AlertsTemplate = () => {
	return <WorkInProgress />
}

```

**Comment by hariscs** [comment]
i can help with this assign it to me.

**Comment by EmmaDawsonDev** [comment]
Go for it :)
