### ISSUE TITLE
Add BreadcrumbsTemplate component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#24]
In the components/templates folder add a BreadcrumbsTemplate.tsx file. Copy the structure of one of the other templates (they're all currently the same apart from name - contents will be added later). Update the component name so it matches the file name.

In the pages/[content].tsx file import the template and add it alphabetically in the correct place between the layout tags ```{page === "breadcrumbs" && <Breadcrumbs />}```

Add the template data to the config file in data/pages.tsx: ```{ name: "Breadcrumbs", href: "/breadcrumbs", content: "breadcrumbs" }```

**Comment by aswin2108** [comment]
I would love to work on it! Could you assign this to me!?

**Comment by EmmaDawsonDev** [comment]
Sure!

**Comment by gaurav-iitb** [comment]
I would also like to work on it

**Comment by aswin2108** [comment]
@gaurav-iitb sure carry-on!
