### ISSUE TITLE
Indicate links which open in a new tab

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#245]
In the footer 2 links open in a new window:
Become a contributor
Support us

These links should have a small icon after them to show that visually. The project already has react icons installed. The following icon can be used and added to the footer component: `BsBoxArrowUpRight`

Import as follows: `import { BsBoxArrowUpRight } from 'react-icons/bs'`

**Comment by hariscs** [comment]
assign this to me

**Comment by ctoffanin** [comment]
Yes, sure @hariscs, go ahead!
