### ISSUE TITLE
Update CSS in MaintainerCard

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#246]
In the file `MaintainerCard.module.css` three of the classes use `var(--primary)` as their colour. However, this colour does not change with light and dark mode and creates contrast issues with black text on the buttons.

Update the border color on `.maintainerContainer` and the background color on `.maintainerImage` and `.linkButton` to 
`var(--primaryLt)`

This card is used on the `About the maintainers` page linked in the footer or on the `/about` route.

**Comment by winniebosy** [comment]
Assign this to me @EmmaDawsonDev

**Comment by ctoffanin** [comment]
Hey @winniebosy. Yes, sure go ahead!

**Comment by EmmaDawsonDev** [comment]
Closed by #247
