### ISSUE TITLE
Accessibility "tip of the day"

### ISSUE THREAD

**Issue by amandamartin-dev** [AccessibleForAll/AccessibleWebDev#249]
This feature is an enhancement/nice to have idea for consideration

**What:**  When a user hits the site, a random tip or "did you know" style bit of information is displayed with a link to the relevant article/info on the website

**Why:** Could be good for a user interested in accessible web dev but not sure where to start or for someone who already knows some things, but is perhaps fed a new idea/tool/tip they weren't aware of and maybe wouldn't search for.

**UI Idea:** Up for discussion, but could be at the top in a banner or somewhere else prominent so it catches the eye.

**Implementation:** Could pull from existing articles on the site if the content makes sense or create a dataset of prompts and their relevant articles which is more manual but you would have better control over the content and experience. ex. "Did you know XX percent of adults in the US have difficulty with low contrast? CTA to an article on designing beautiful high contrast UI"

**Comment by EmmaDawsonDev** [comment]
I absolutely love this idea! We could start by adding the tips into a json file and then move over to a database. I already have another idea which needs a database of tips so that would definitely be great to use it in both cases.

**Comment by amandamartin-dev** [comment]
That's a great way to implement for now an gives me another "follow up" idea. Once the way to ingest/display the json is up and running could create a way for folks to submit "tip of the day ideas" to crowd source more info and give another way for ppl to contribute

1. Create an issue template with all the fields required for the json
 *potentially need to have a place for a user to state in a description the source for their tip (in case it's unclear)

3. Update the docs about how to submit a tip and best practices for what a quality tip looks like

**Comment by EmmaDawsonDev** [comment]
Sounds great! Let's break this down into smaller issues that people could work on (please add anything I miss):

- [ ] Design a Tip of the Day component that will display on the home page (both mobile and desktop)
- [ ] Create a Tip of the Day component and corresponding story with a hard-coded tip to start with
- [ ] Create a json file within the data folder that can hold all the tips
- [ ] Decide on a structure for each tip (maybe id, tip, link?) and a few tips to start with
- [ ] Add logic for showing a random tip instead of the hard-coded one
- [ ] Update the docs with how to add a tip

**Comment by amandamartin-dev** [comment]
I think this covers everything and anything else could be added as it comes up anyhow.  I am happy to help with this effort (or anything else you are needing right now in this project), but designing is not my specialty outside of the typical style web components so perhaps I could jump in after.  I will keep my eye on it.  

Do you want to drop the issues to be created in the discord so that folks become more aware of this repo and maybe contribute or would you prefer that we just make them all now?  I'm happy to set up the issues, lmk!

**Comment by hariscs** [comment]
@EmmaDawsonDev would love to work on the implementation of this feature

**Comment by EmmaDawsonDev** [comment]
Apologies for answering so late, it's been a busy few weeks.

I'll make all of these points into individual issues so that they're easier to keep track of. I think we can make a basic component without a special design, based on other elements already created in the site. We can always improve it later.

**Comment by EmmaDawsonDev** [comment]
@hariscs feel free to let me know which issue you want to work on and I'll assign you

**Comment by yashfalke77** [comment]
@EmmaDawsonDev i would also like to work on this features, if anything is available do let me know

**Comment by EmmaDawsonDev** [comment]
Hi Yash, 

There is currently a component but there are no tips or logic for fetching them yet so the component is hidden. I guess we could hard code something in json to begin with, maybe 7 tips which show on a specific day each week. Let me know if you want to work on it or have a better idea 😊

**Comment by Neha** [comment]
Hey @EmmaDawsonDev I can pick this issue.

A few thoughts here:

1. Have a dedicated page to keep all tips of the day in one place
2. When the user comes on site we will display the tip of the day + read more (link to the tip of the day page)
3. Contribution link  can we on the tip of the page day

Question: Are we going to have the 'tip of the day' as an alert component? 

Cheers.

**Comment by EmmaDawsonDev** [comment]
Hi Neha! There is already a component but it’s currently hidden as we have no tips. Eventually I’d like to have a database of tips to start from which people can contribute to but for now the idea is to hard code a few tips in json and show a different one each day, looping through and back to the beginning when they run out. 

The tip of the day will appear on the home page of the site under the general introduction. Any links will link directly to outside pages like blog posts or other resources. I don’t think it needs to be an alert. You’re more than welcome to hard code a list of a few tips if you’d like and see if you can get them to display on the home page.

**Comment by Neha** [comment]
One suggestion regarding DB:

Instead of introducing DB we can keep the JSON file. As we are not querying, searching, or category-wise dividing the tips. For contribution we can request contributors to add in JSON and raise the PR against the JSON.

wyt @EmmaDawsonDev
