### ISSUE TITLE
Add ButtonsTemplate component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#25]
In the components/templates folder add a ButtonsTemplate.tsx file. Copy the structure of one of the other templates (they're all currently the same apart from name - contents will be added later). Update the component name so it matches the file name.

In the pages/[content].tsx file import the template and add it alphabetically in the correct place between the layout tags ```{page === "buttons" && <Buttons />}```

Add the template data to the config file in data/pages.tsx: ```{ name: "Buttons", href: "/buttons", content: "buttons" }```

**Comment by Nikhil-1503** [comment]
Hi Emma!
Can I work on this one?
Thank you

**Comment by EmmaDawsonDev** [comment]
Sure! Just wait until October 1st to make the PR if you are taking part in Hacktoberfest :)
