### ISSUE TITLE
Create a design for "Tip of the day" component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#251]
On the front page we want to include a random "Tip of the Day". Please use the current design as inspiration for this component.

The component will have the following information:
title
tip
and possibly a link (not mandatory)

**Comment by hariscs** [comment]
assign me this

**Comment by EmmaDawsonDev** [comment]
Sure!

**Comment by MohitBansal321** [comment]
Can i Work on this issue

**Comment by mud1tx** [comment]
@EmmaDawsonDev I can work on this if no one is working on this?

**Comment by EmmaDawsonDev** [comment]
I've got someone helping to do a whole site redesign at the moment so I'm going to put this on hold until that's done
