### ISSUE TITLE
Add color coding to the code block component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#255]
Currently everything in the codeblock is showing white.

It would be great if there could be some form of color-coded syntax highlighting for html, css and js that follows the theme.

**Comment by PiseAtharva** [comment]
Hi Emma, I beleive Prism Library [Source](https://prismjs.com/) can help with CodeBlock wrapping the codesnippet. Is it fine if I try to work on this task ?

**Comment by EmmaDawsonDev** [comment]
I have looked into using a package before but so far I've been unsuccessful. I tried react-syntax-highlighter but that didn't work. You're more than welcome to try Prism if they have a fully accessible theme where all colors have a color contrast of at least 4.5:1.

**Comment by PiseAtharva** [comment]
> I have looked into using a package before but so far I've been unsuccessful. I tried react-syntax-highlighter but that didn't work. You're more than welcome to try Prism if they have a fully accessible theme where all colors have a color contrast of at least 4.5:1.

Hey, thanks for the heads-up, I tried react-syntax-highlighter with dracula theme and it worked very nicely (attaching screenshots), their contrast are also higher than WCAG AAA standards (lowest was pink with 5.89, rest two color codes were above 10 😄 ). What do you think, lemme know ?

SyntaxHighlighter Code that replaced the "pre" tag: 
`<SyntaxHighlighter language="html" style={dracula}>{codeSnippet} </SyntaxHighlighter>`

![image](https://user-images.githubusercontent.com/88548999/218820602-4fa68b8e-6a4a-4536-ae81-e64c920f20d3.png)
![image](https://user-images.githubusercontent.com/88548999/218819991-35b3b4b0-454c-4400-887b-25156cf9fa4a.png)

Incase we want to specify the language (html, css, js) for particular codesnippet, lemme know about that accordingly. So far I found only md elements inside buttonsTemplate and imagesTemplate.

**Comment by EmmaDawsonDev** [comment]
That’s looking super nice so far! Yes, I think being able to specify the language will be useful in the future. So far I’ve only used html/css but there’s bound to be some js coming later too.

**Comment by MohitBansal321** [comment]
I am also working on it can i continue?

**Comment by MohitBansal321** [comment]
![Screenshot 2023-02-15 002629](https://user-images.githubusercontent.com/78220157/218831384-9e17e056-5cab-41d9-88f3-5b9211b66da1.png)

**Comment by EmmaDawsonDev** [comment]
I think PiseAtharva is almost done on this one but feel free to choose a different issue that’s not already assigned 😊

**Comment by PiseAtharva** [comment]
Saw this in ImageTemplates at very end, should i be concerned about this ? If not then I am ready for the 1st PR
![image](https://user-images.githubusercontent.com/88548999/218948775-f55e1cca-01f2-42a8-b300-b07165ac5ff3.png)
![image](https://user-images.githubusercontent.com/88548999/218949059-90ec8388-681e-46bf-9e86-7cef25c47862.png)

**Comment by EmmaDawsonDev** [comment]
No, that refers to when the content was last written/re-written so the reader knows how up to date the information is. Feel free to make your PR 😊
