### ISSUE TITLE
Add ability to copy/paste code block

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#256]
It would be good if there were a button in the top-right corner of the codeblock that allowed users to copy the code with one click of the button.

**Comment by mithindev** [comment]
Hello @EmmaDawsonDev , I would love to work on this issue. Can you please assign it to me.😊

**Comment by ctoffanin** [comment]
Hello @mithindev. Yes, go ahead!

**Comment by MohitBansal321** [comment]
This issue still open ?

**Comment by mithindev** [comment]
I am sorry, I am still working on it.

**Comment by PiseAtharva** [comment]
Hey Mithin, I saw it was taking ya bit longer than usual, thought I can help ya with the Issue at hand. If you can take a look at these [changes ](https://github.com/PiseAtharva/AccessibleWebDev/tree/issue-%23256/components/CodeBlock) maybe it can work ?

**Comment by EmmaDawsonDev** [comment]
How's this one going @mithindev? Are you still working on it or do you want to let someone else take over?

**Comment by marksist300** [comment]
Is this issue still open?

**Comment by EmmaDawsonDev** [comment]
@marksist300 yes, I believe so
