### ISSUE TITLE
Add AlertsTemplate component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#26]
In the components/templates folder add a AlertsTemplate.tsx file. Copy the structure of one of the other templates (they're all currently the same apart from name - contents will be added later). Update the component name so it matches the file name.

In the pages/[content].tsx file import the template and add it alphabetically in the correct place between the layout tags ```{page === "alerts" && <Alerts />}```

Add the template data to the config file in data/pages.tsx: ```{ name: "Alerts", href: "/alerts", content: "alerts" }```

**Comment by stevenovak123** [comment]
Hey Emma.

I'd Like to take this up.

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead.
