### ISSUE TITLE
Create PageLastUpdated component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#261]
Currently at the bottom of the Buttons and Images pages there is a `<p>` tag which shows when the page was last updated.

<img width="194" alt="image" src="https://user-images.githubusercontent.com/57045550/219852462-ac6c1d4e-fbf2-4c75-bcf8-e93821d99c19.png">

Since this will be used on every page it would be good to turn it into a reusable component that takes the date as a prop.

**Comment by Girishbari** [comment]
let me handle it, please assign it to me

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead.
