### ISSUE TITLE
Add ModalsTemplate component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#27]
In the components/templates folder add a ModalsTemplate.tsx file. Copy the structure of one of the other templates (they're all currently the same apart from name - contents will be added later). Update the component name so it matches the file name.

In the pages/[content].tsx file import the template and add it alphabetically in the correct place between the layout tags ```{page === "modals" && <Modals />}```

Add the template data to the config file in data/pages.tsx: ```{ name: "Modals", href: "/modals", content: "modals" }```

**Comment by TAKANOME-DEV** [comment]
Hi @EmmaDawsonDev I would like to take this one :pray:

**Comment by EmmaDawsonDev** [comment]
Sure!

**Comment by muditchoudhary** [comment]
Hello, @EmmaDawsonDev I think @TAKANOME-DEV not working on this, so can I work on this?

**Comment by EmmaDawsonDev** [comment]
Sure, no problem. 

@TAKANOME-DEV if you decide later that you do want to join in just let me know and I’ll try to find another issue you can have
