### ISSUE TITLE
Change link in WorkInProgress component to Github Discussions

### ISSUE THREAD

**Issue by celiackelly** [AccessibleForAll/AccessibleWebDev#277]
**Issue / Feature Request**
Currently, on the pages which are works in progress, there is a link with the text ["Let us know what information you're looking for"](https://github.com/AccessibleForAll/AccessibleWebDev), which links to the main Github repo page/readme. 
![image](https://user-images.githubusercontent.com/81911167/233087162-48f1dbb1-daf7-47fe-8ede-444503405236.png) 

However, the place to add information you'd like to see on that page is actually the [Github Discussions page for the repo](https://github.com/AccessibleForAll/AccessibleWebDev/discussions), which has a discussion thread and linked Google doc for each work in progress page. The readme talks about how to contribute code and add an issue, but it does not mention or link to the Discussions page.  If users don't explore and click on the Discussions tab, they'll never find the right spot to suggest content for inclusion on the page. 

**Solution**
I think the "Let us know what information you're looking for" link in the WorkInProgress component should link to the Discussions page (https://github.com/AccessibleForAll/AccessibleWebDev/discussions), rather than the main page of the repo. It's a small change, but it would be clearer for users looking to contribute to the discussion of what content should be on the work in progress pages. 

**Alternatives**
- One alternative would be to leave the link as is, but to add a section to the readme that links to the Discussions page and describes how to contribute suggestions for content.

**Comment by ArslanYM** [comment]
I would love to fix this issue.

**Comment by celiackelly** [comment]
Since I posted the issue, I was hoping to be assigned to it, if the maintainers agree that this change should be made.

**Comment by EmmaDawsonDev** [comment]
I really like that idea, thanks for the suggestion @celiackelly, I have assigned it to you.
