### ISSUE TITLE
Add LinksTemplate component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#28]
In the components/templates folder add a LinksTemplate.tsx file. Copy the structure of one of the other templates (they're all currently the same apart from name - contents will be added later). Update the component name so it matches the file name.

In the pages/[content].tsx file import the template and add it alphabetically in the correct place between the layout tags ```{page === "links" && <Links />}```

Add the template data to the config file in data/pages.tsx: ```{ name: "Links", href: "/links", content: "links" }```

**Comment by Aniket1026** [comment]
Hey @EmmaDawsonDev would love to work on this 😄

**Comment by EmmaDawsonDev** [comment]
Hi @Aniket1026 there is already a pull request for this one but let me create an issue for another component template you can add

**Comment by Aniket1026** [comment]
Thank you emma 😄
