### ISSUE TITLE
Code snippets are not responsive

### ISSUE THREAD

**Issue by Soyeb01** [AccessibleForAll/AccessibleWebDev#282]
## Is your feature request related to a problem? Please describe.**
The Code snippet block is not responsive for mobile devices , *overflow should not be blocked* in "CSS" to show how its should look in desktop view in code editors.

## To Reproduce
In Mobile devices :
1. Go to 'Headings Section from Side navbar'
2. Click on 'Headings'
3. Scroll down to 'Code snippet to show nesting of different headings'

## Describe the solution you'd like
The snippet should show **how to nest heading sections within one another in sequential order.**
It would be good if the blocks give same code view as the desktop view . It would be **more clear to see and easy to read.**

### In **Heading section**
![accessibleweb dev_headings](https://user-images.githubusercontent.com/98175646/233860911-9515bccc-199d-435a-b0b9-50a25fa877a9.png)

**Comment by EmmaDawsonDev** [comment]
Indeed. I think this is being caused by the 'wrapLongLines' prop. However, without it then the blocks become unresponsive. We need to find a way to make the code block scrollable if necessary and at the same time if it's scrollable it needs to also be keyboard accessible.

**Comment by EmmaDawsonDev** [comment]
Adding this here as a potential pattern to follow https://github.com/dequelabs/cauldron/blob/develop/packages/react/src/components/Code/index.tsx

**Comment by Neha** [comment]
Hey, I would like to pick this issue

**Comment by EmmaDawsonDev** [comment]
Sure @Neha

**Comment by Neha** [comment]
Facing this issue when doing `yarn install`

any pointers to resolve this issue?

<img width="1462" alt="Screenshot 2023-04-30 at 8 55 01 AM" src="https://user-images.githubusercontent.com/61655/235342521-07c6b0cb-f38c-4d70-b7ee-c10c38f71910.png">

**Comment by hariscs** [comment]
> Facing this issue when doing `yarn install`
> 
> any pointers to resolve this issue?
> 
> <img width="1462" alt="Screenshot 2023-04-30 at 8 55 01 AM" src="https://user-images.githubusercontent.com/61655/235342521-07c6b0cb-f38c-4d70-b7ee-c10c38f71910.png">
> 
> cc @EmmaDawsonDev 

Hey @Neha, the `install` command will not work with yarn, instead run `yarn` or `yarn add`

**Comment by Neha** [comment]
Thank you @hariscs  Sure. After doing `yarn`  the issue is still there.

Shall we update our readme? It is mentioned in readme to use `yarn install`?

**Comment by EmmaDawsonDev** [comment]
@hariscs yarn install is the correct command to use.

@Neha from the pictures it looks like the version of node is not matching. Can you check your node version by typing `node -v` in the terminal.

**Comment by EmmaDawsonDev** [comment]
Did you manage to get it up and running @Neha or are you still getting errors?

**Comment by Neha** [comment]
@EmmaDawsonDev yes, I am able to run it on the local. All good and ready to work on the issue. Thanks

**Comment by EmmaDawsonDev** [comment]
Great! Glad you got it working. Feel free to let me know if you run into any other issues

**Comment by Neha** [comment]
Before I raise the PR, is this the expectation here?

(please ignore the theme as of now. Styling is WIP)

<img width="542" alt="Screenshot 2023-05-05 at 10 13 59 PM" src="https://user-images.githubusercontent.com/61655/236570213-b14d1e3b-2732-4d19-a87e-18756dc168f1.png">

**Comment by EmmaDawsonDev** [comment]
Hi @Neha the styling and layout should match how it looks on desktop and the rows should not wrap on smaller screens. Instead the overflow should be hidden and the box should be scrollable along the x axis when the content doesn't fit on the screen. It should be possible to control the scroll with the keyboard arrow keys.

Screen shot with terrible handwriting:
<img width="312" alt="Screenshot 2023-05-06 145815" src="https://user-images.githubusercontent.com/57045550/236625791-4a4cec22-003a-4a7d-bcea-4319475c7567.png">
