### ISSUE TITLE
To improve the UI of AccessibleWebDev

### ISSUE THREAD

**Issue by aashay28** [AccessibleForAll/AccessibleWebDev#285]

**Comment by EmmaDawsonDev** [comment]
Please add some details about how you think the design can be improved

**Comment by aashay28** [comment]
yes, Sure

- need to add logo.
- instead of theme dropdown toggle switch should be used.
- Footer need some margin, height and change in view.

And also there are some suggestions in body area:

- Left and right area have more margin
- To indicators of a page are not need

![changes](https://user-images.githubusercontent.com/108337259/235447925-d9a84127-b87e-418d-b009-f1129e7702c8.png)

**Comment by aashay28** [comment]
1. when a user clicks on the left navigation menu - only the main content should render.
2. left sidebar should be separate from main content :
- current: while user scroll the main content, left navigation bar is also affecting and user find it empty if the content is lengthy.
- change: while user scroll the main content, left navigation should not affect and it should have its own scroll bar.

**Comment by aashay28** [comment]
It was a pleasure to be able to contribute my thoughts and ideas. Thank you for valuing my input and considering my feedback.

**Comment by EmmaDawsonDev** [comment]
Thanks for your input. I’ll break some of them out into separate issues so they’re easier to work on.

**Comment by aashay28** [comment]
> Thanks for your input. I’ll break some of them out into separate issues so they’re easier to work on.

Perfect !

**Comment by EmmaDawsonDev** [comment]
Thanks for the suggestions! Most have now been implemented. Please feel free to suggest further changes if you have any ideas.
