### ISSUE TITLE
"skip to main content" is visible before header

### ISSUE THREAD

**Issue by aashay28** [AccessibleForAll/AccessibleWebDev#286]
**Describe the bug**
 "skip to main content" is displayed before the header of a website, but is it useful?

**To Reproduce**
1. inspect the body of website
2. select the div 
3. Add margin top
4. See the text "skip to main content"

**Screenshots**
![hidden text](https://user-images.githubusercontent.com/108337259/235438258-d0fa57d7-dec4-43c4-becb-823715d29068.png)

**Comment by EmmaDawsonDev** [comment]
This is an accessibility feature which allows keyboard users to skip over large blocks of navigation elements when jumping between different pages. Is there something that doesn't work with it?

**Comment by aashay28** [comment]
> This is an accessibility feature which allows keyboard users to skip over large blocks of navigation elements when jumping between different pages. Is there something that doesn't work with it?

is it under development? I can't find the skip element when scrolled the content !

**Comment by EmmaDawsonDev** [comment]
No, it should be finished. It should jump to the main content and allow a keyboard user to bypass tabbing through all the navigation links.

**Comment by aashay28** [comment]
okay, got it.
