### ISSUE TITLE
Theme picker doesn’t toggle closed.

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#290]
The theme picker button should toggle the pop up open and closed. This works with keyboard but with mouse it triggers it to open on every click. It should instead close the pop up if it’s already opened.

**Comment by thehashmap** [comment]
Hi! I would like to work on this issue. 
Could you please assign it to me?

**Comment by EmmaDawsonDev** [comment]
Sure @thehashmap let me know if you need anymore details. Otherwise you're good to go 😊
