### ISSUE TITLE
Bug: focus doesn’t move from page navigation

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#292]
If you tab to the ‘on this page’ navigation section and then click enter on one of the links visually it scrolls to the appropriate section. However, the focus remains on the link pressed to when you try to continue tabbing it jumps back up to the ‘on this page’ section instead of focusing on the next interactive element in the chosen section.

**Comment by ArslanYM** [comment]
@muditchoudhary Looks like a solvable issue. Try it out

**Comment by ArslanYM** [comment]
@mud1tx Looks like a solvable issue. Try it out

**Comment by mud1tx** [comment]
@ArslanYM @EmmaDawsonDev giving this issue a try.

**Comment by mud1tx** [comment]
@EmmaDawsonDev Is this issue still open?

**Comment by EmmaDawsonDev** [comment]
Yes, would you like to be assigned @mud1tx ?

**Comment by mud1tx** [comment]
@EmmaDawsonDev yes I can work on it, but can you please explain the issue.

**Comment by mud1tx** [comment]
@EmmaDawsonDev If you wait for 2 sec after clicking the link everything is working don't know why it is taking that much time. as I click the link on navbar it should instantly move to that page but there is a delay of atmost 2sec.

**Comment by mud1tx** [comment]
@EmmaDawsonDev I think it works like that only don't know how to solve this issue.

**Comment by EmmaDawsonDev** [comment]
Hmm, That's strange. I'm not home right now so can't investigate. I'll take another look when I'm home next week

**Comment by Neha** [comment]
Check https://www.w3.org/WAI/fundamentals/accessibility-intro/ in this they have the behaviour where the focus is also shifting to the appropriate section.

**Solution**:

Moving the focus to the appropriate section requires a small code change we can wrap the `H2` (section heading) with `a` tag and this will solve this issue. In addition to shifting the focus we should also do some visual style change to indicate the focus has changed (especially for large screens) 

@EmmaDawsonDev

**Comment by prasarCodes** [comment]
> Check https://www.w3.org/WAI/fundamentals/accessibility-intro/ in this they have the behaviour where the focus is also shifting to the appropriate section.
> 
> **Solution**:
> 
> Moving the focus to the appropriate section requires a small code change we can wrap the `H2` (section heading) with `a` tag and this will solve this issue. In addition to shifting the focus we should also do some visual style change to indicate the focus has changed (especially for large screens)
> 
> @EmmaDawsonDev

Can confirm that this solves the issue! Also, can you please hint at what visual changes you are suggesting for the focus change?

**Comment by EmmaDawsonDev** [comment]
I've taken a look at the code from the w3c above and they are not wrapping anything in anchor tags, they are just using ids to reference links in the same way that it is being done in this repo so I'm not really sure why this is not working. There must be something slightly wrong in the code somewhere

**Comment by EmmaDawsonDev** [comment]
I think I've worked out the problem and it's due to using the NextJS `Link` component instead of just an anchor tag.

To fix this in the `NavPage` component, change line 18 from `<Link href={item.href}>{item.linkName}</Link>` to `<a href={item.href}>{item.linkName}</a>` and see if that solves the problem.

@mud1tx would you like to have a go or is anyone else interested?

**Comment by Neha** [comment]
I can take this issue @EmmaDawsonDev

**Comment by EmmaDawsonDev** [comment]
Thanks Neha!

**Comment by Neha** [comment]
Hey, @EmmaDawsonDev any style change I need to add to the focused section? Eg: outline or background colour that will fade after a few seconds?
