### ISSUE TITLE
[feat] Internal Docs Style Guide 

### ISSUE THREAD

**Issue by CBID2** [AccessibleForAll/AccessibleWebDev#299]
**Is your feature request related to a problem? Please describe.**
I noticed that there is no specific style guide to maintain the Documentation for the repos. 

**Describe the solution you'd like**
Create an internal docs style guide. It would not only help people gain experience in working with docs, but also makes the content appear organized. 

**Describe alternatives you've considered**
Nothing really. 

**Additional context**
N/A

**Comment by EmmaDawsonDev** [comment]
This is a great idea! Would you like to be assigned?

**Comment by CBID2** [comment]
> This is a great idea! Would you like to be assigned? 

Sure @EmmaDawsonDev! :)

**Comment by CBID2** [comment]
> > This is a great idea! Would you like to be assigned?
> 
> Sure @EmmaDawsonDev! :)

Hi @EmmaDawsonDev! :) Here's [my PR for the docs guide](https://github.com/AccessibleForAll/AccessibleWebDev/pull/301)! :)
