### ISSUE TITLE
Align-left to heading 1

### ISSUE THREAD

**Issue by YuriDevAT** [AccessibleForAll/AccessibleWebDev#302]
**Is your feature request related to a problem? Please describe.**
To avoid jumping of the heading when clicking on different items in the side panel, it may would be a good idea to align the heading (title of the current component) to the left (initial value).

**Describe the solution you'd like**
Change `text-align: center` to `text-align: left` or delete text-align to set it back to initial value. In addition, set `max-width: 1200px;` and add an `auto` value to margin to align the heading with the main content like `margin: 1rem auto;` 

![heading](https://github.com/AccessibleForAll/AccessibleWebDev/assets/54622834/791e6f65-ebac-4690-987d-e7390c7da712)

**Preview**
![image](https://github.com/AccessibleForAll/AccessibleWebDev/assets/54622834/4b08bb33-24a8-488a-943a-f414f778e7fe)

**Comment by EmmaDawsonDev** [comment]
Thanks for the suggestion Julia! We're actually trying to do a bit of a redesign at the moment which will move the navigation and the heading to make better use of the space. You should be able to view it on [Figma](https://www.figma.com/file/m0ct4CzGoX8PgkYPT3MdqV/AccessibleForAll-branding?type=design&node-id=0%3A1&t=rwxYMyGPxTZ3PZLm-1) and if you want edit rights then just let me know.

**Comment by YuriDevAT** [comment]
Great. I saw this issue already and agree that this would be a good enhancement 😄
