### ISSUE TITLE
Add ListsTemplate component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#31]
In the components/templates folder add a ListsTemplate.tsx file. Copy the structure of one of the other templates (they're all currently the same apart from name - contents will be added later). Update the component name so it matches the file name.

In the pages/[content].tsx file import the template and add it alphabetically in the correct place between the layout tags ```{page === "lists" && <Lists />}```

Add the template data to the config file in data/pages.tsx: ```{ name: "Lists", href: "/lists", content: "lists" }```

**Comment by Aniket1026** [comment]
Hello @EmmaDawsonDev would love to work on this. Can you assign me?😄
