### ISSUE TITLE
Overflow on small screen sizes

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#311]
**Describe the bug**
A user reported that on their iphone 12 mini (width 320px) that there is some overflow on the x axis.

**Expected behavior**
No overflow on x-axis. Site works responsively down to 320px.

**Screenshots**
![image](https://github.com/AccessibleForAll/AccessibleWebDev/assets/57045550/02afba38-9d10-4b12-8320-4d33e507fa5c)

**Comment by jgyfutub** [comment]
Hi this is vedant pandey can i work on this issue?

**Comment by EmmaDawsonDev** [comment]
Sure!

**Comment by Rohan-Hazari** [comment]
Hey @jgyfutub are you still working on the issue?

**Comment by jgyfutub** [comment]
I apologize but I was not able to understand this issue ,so if somebody interested can take this.

**Comment by Rohan-Hazari** [comment]
Okay np vedant @EmmaDawsonDev Can I try to solve this issue please?

**Comment by EmmaDawsonDev** [comment]
Sure @Rohan-Hazari

**Comment by Rohan-Hazari** [comment]
@EmmaDawsonDev I was unable to locate any overflow. I checked it locally, on the live site, and on my own smartphone, not just at 320px but also on a device with a smaller width (Galaxy Fold 280px). I appreciate the chance, though. I'm unassigning myself from this issue.

**Comment by EmmaDawsonDev** [comment]
Ok, thanks so much for checking! This one seems elusive as I can’t replicate it locally and don’t have the same phone to check it

**Comment by at-the-vr** [comment]
Hey Emma, can u check this extension for Mobile Simulator (It gives 99% accurate visual simulation for your web app) [Link to Mobile Simulator on Google Chrome](https://chrome.google.com/webstore/detail/mobile-simulator-responsi/ckejmhbmlajgoklhgbapkiccekfoccmk?hl=en).
The only overflow found is in the Code Snippets as intended, everything else looks fairly good tbh.
There is a small chance that the User might have zoomed a bit or is using a different layout (as in increased size of text, icons for readability)

**Comment by ctoffanin** [comment]
Hi @EmmaDawsonDev!
I have a 12 mini. I tried with Safari, Chrome and Firefox, and I can't reproduce the overflow either.

**Comment by EmmaDawsonDev** [comment]
@ctoffanin how are you? thank you so much for checking! Maybe this got fixed in the site redesign 🤷‍♀️ I will close it for now and if anyone else reports similar issues in the future we can look into it further.
