### ISSUE TITLE
Links are too close together

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#312]
**Describe the bug**
Lists of links on the pages and in the footer are too close together making it hard for people with poor dexterity to click the correct link. Links should be spaced so that they have a minimum height of 44px. Since their font size is 16px this means they should have a margin top and bottom of 14px each so that the total height is 44px.

**Screenshots**
<img width="231" alt="Screenshot 2023-06-06 155535" src="https://github.com/AccessibleForAll/AccessibleWebDev/assets/57045550/44eef2e7-218b-4afc-825f-a7972025fe32">

**Comment by thehashmap** [comment]
Hi, I would like to fix this issue

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead!

**Comment by EmmaDawsonDev** [comment]
I've fixed the ones on the pages as I was working on the pages today. The ones in the footer still need fixing on mobile.
