### ISSUE TITLE
Site Redesign

### ISSUE THREAD

**Issue by LadyBluenotes** [AccessibleForAll/AccessibleWebDev#313]
# Site Redesign

Hello hello! I worked with @EmmaDawsonDev to redesign the site to more align with what she was looking for. This will be an issue outlining some of the details for this redesign. Below, you'll find a screenshot of the design.

## Light Mode

<img width="886" alt="A screenshot that depicts the new Accessible Web Dev website changes for the light mode." src="https://github.com/AccessibleForAll/AccessibleWebDev/assets/98355961/14ccdc1a-cf7f-4186-ade8-c973cefcea21">

Background: #FFFFFF
Text: #1C2541
Secondary (borders, nav link hover backgrounds): #28968C

## Dark Mode

<img width="682" alt="A screenshot that depicts the new Accessible Web Dev website changes for the dark mode. " src="https://github.com/AccessibleForAll/AccessibleWebDev/assets/98355961/dacecc53-eb61-4975-a7d6-857533f51e8d">

Background: #161E35
Text: #FFFFFF
Secondary (borders, nav link hover backgrounds): #53FDEE

## Other Styling

All text will be in Noto Sans.
Headings will be in the font weight BOLD.
Navigation links will be in the font weight MEDIUM.
Body will have normal font weight.

Heading sizes will need to be clarified by @EmmaDawsonDev. 
Body text will be 1REM.

**Comment by DIWAKARKASHYAP** [comment]
i want to work on this

**Comment by EmmaDawsonDev** [comment]
@LadyBluenotes did you want assigning to this? I forgot to ask you

**Comment by LadyBluenotes** [comment]
@EmmaDawsonDev 

It may be a good idea to figure out the best way to break this down into more manageable chunks - I think it is a massive undertaking for one individual to take on, additionally, it could give some other people the chance to try out open source coding work. 

What do you think?

**Comment by EmmaDawsonDev** [comment]
I agree, I will look at it tomorrow and plan how to do it without breaking things 😊

**Comment by DIWAKARKASHYAP** [comment]
@LadyBluenotes can you send me the logo.png file

**Comment by EmmaDawsonDev** [comment]
@DIWAKARKASHYAP I'm actually going to redo the logo so the one in the image isn't quite right

**Comment by DIWAKARKASHYAP** [comment]
@EmmaDawsonDev ok , i leave the logo part

**Comment by DIWAKARKASHYAP** [comment]
@EmmaDawsonDev where i show this 
![image](https://github.com/AccessibleForAll/AccessibleWebDev/assets/94478026/1154379e-40e6-400d-b408-32ff26f77100)

**Comment by LadyBluenotes** [comment]
@DIWAKARKASHYAP it will be a heading within the main part of the page.

**Comment by DIWAKARKASHYAP** [comment]
@LadyBluenotes you mean this ?
![image](https://github.com/AccessibleForAll/AccessibleWebDev/assets/94478026/7153cf04-ce71-4b82-b402-29fab52a6405)

**Comment by EmmaDawsonDev** [comment]
I added a few of the tasks for this as separate issues, like updating the font and moving the header. I will continue to break them down into smaller issues so please ask to be assigned to anything you want to work on in the relevant issue as that way it's easier to keep track of who is doing what.

**Comment by DIWAKARKASHYAP** [comment]
@EmmaDawsonDev 
OK , its good , can i raise the issue ?

**Comment by DIWAKARKASHYAP** [comment]
@EmmaDawsonDev 
Can I raise some issue regarding this , or you gonna create all ?

**Comment by LadyBluenotes** [comment]
@DIWAKARKASHYAP not to speak for Emma, but I imagine she will raise the appropriate issues for the site redesign, for which you can request to be assigned to the ones that are available.

Typically issues are used to rectify any errors with the site or information in the pages.

**Comment by EmmaDawsonDev** [comment]
Thanks Sarah!

@DIWAKARKASHYAP I think since there's quite a few things to keep track of it's best if I post all the issues related to the redesign. That way I can make sure nothing breaks and things can be changed incrementally. Feel free to ask to be assigned to any that you'd like to work on.

**Comment by DIWAKARKASHYAP** [comment]
@EmmaDawsonDev are you have any update ?

**Comment by LadyBluenotes** [comment]
@DIWAKARKASHYAP If you look within issues, you will find the issues relevant to the redesign.
