### ISSUE TITLE
Update font family to Noto Sans

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#314]
Import NotoSans from google fonts.

Set the font family on the body to Noto Sans, leaving the other current fonts as fallback options.

**Comment by mohibkay** [comment]
Hey, @EmmaDawsonDev, could you please assign this issue to me?
I would like to work on adding NotoSans to the project.

**Comment by EmmaDawsonDev** [comment]
Sure! Thanks 😊
