### ISSUE TITLE
Move h1 from layout into each page

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#315]
- [ ] Remove the h1 from the Layout component
- [ ] Remove the headerTitle prop from the interface and props in the Layout component
- [ ] Remove the h1 styles from the Layout styles file
- [ ] Add a h1 to the index page before the first section. Remove the headerTitle prop from Layout and add the text directly into the h1.
- [ ] Add a h1 to the [content] page before as the first element inside the fragment. Remove the headerTitle prop from Layout and add the text directly into the h1
- [ ] Add a h1 to the about page before the first section. Remove the headerTitle prop from Layout and add the text directly into the h1.
- [ ] Add a h1 to the 404 page before the first div. Remove the headerTitle prop from Layout and add the text directly into the h1.
- [ ] Add a font-size for the h1 into the global styles file. Set it to 2.5 rem.

**Comment by jgyfutub** [comment]
can I work on this one?

**Comment by EmmaDawsonDev** [comment]
Sure 😊
