### ISSUE TITLE
Move .infoSection class

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#317]
Create a TemplateSection.module.css file and then move the `.infoSection` class from globals.css to the new file. Import it into the template.

**Comment by jgyfutub** [comment]
can I work upon this issue??

**Comment by at-the-vr** [comment]
You don't need to take all issues (especially when they are similar in nature). Let som1 else have them 👍

**Comment by EmmaDawsonDev** [comment]
@jgyfutub I think it's best to get your current PRs merged before getting anything else assigned. Once those are completed then you can be assigned others.

**Comment by jgyfutub** [comment]
okk no problem....

**Comment by itsdevdeepak** [comment]
I would like to work on this.

**Comment by EmmaDawsonDev** [comment]
Sure! Go ahead @itsdevdeepak
