### ISSUE TITLE
Add FormsTemplate component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#32]
In the components/templates folder add a FormsTemplate.tsx file. Copy the structure of one of the other templates (they're all currently the same apart from name - contents will be added later). Update the component name so it matches the file name.

In the pages/[content].tsx file import the template and add it alphabetically in the correct place between the layout tags ```{page === "forms" && <Forms />}```

Add the template data to the config file in data/pages.tsx: ```{ name: "Forms", href: "/forms", content: "forms" }```

**Comment by Giriraj-Roy** [comment]
Hello ma'am,
I have gone through the repository and the given instructions. The issue seems to attract my interest and excites me to work on it. I humbly wait for you to assign the task to me if your analysis of my profile allows.

Yours Sincerely,
Giriraj Roy.

**Comment by adityabhattad2021** [comment]
Hey, can I work on this one?

**Comment by EmmaDawsonDev** [comment]
Assigning this to @adityabhattad2021 as I already assigned another issue to @Giriraj-Roy

**Comment by adityabhattad2021** [comment]
Hey are you planning to add more issues?

**Comment by EmmaDawsonDev** [comment]
Probably. I’m trying to spread it out and share them among different people since they are newcomer-friendly and I want to help so many as possible get pull requests for hacktoberfest.

**Comment by adityabhattad2021** [comment]
Hey @EmmaDawsonDev there is no templates folder in components should I add it?

**Comment by EmmaDawsonDev** [comment]
Ah sorry just realised the mistake in my first post. I think the folder is called contentTemplates not just templates. No need to add a new folder

**Comment by adityabhattad2021** [comment]
Finished working on this one will make a PR on 01 October🙂. Btw is there any other issue for me to work on?

**Comment by EmmaDawsonDev** [comment]
Great! 

I am afk until Saturday so unfortunately I can’t check what else needs doing at the moment. But maybe I can find some more tasks at the weekend
