### ISSUE TITLE
Add a Installation Section in Readme

### ISSUE THREAD

**Issue by kumarankit999** [AccessibleForAll/AccessibleWebDev#323]
**Is your feature request related to a problem? Please describe.**
There is not a Installation Section in this Project Readme

**Describe the solution you'd like**
There should be a Section for Installation of this project after forking it.

**Describe alternatives you've considered**
It will be very Useful for New-comers who want to run this project in own local system.

**Additional context**

**Comment by EmmaDawsonDev** [comment]
Hi Ankit, thanks for the suggestion. In order to keep the readme concise the installation instructions are in the contributing guidelines which are linked in the readme
