### ISSUE TITLE
Navigation Styling 

### ISSUE THREAD

**Issue by DIWAKARKASHYAP** [AccessibleForAll/AccessibleWebDev#324]
![image](https://github.com/AccessibleForAll/AccessibleWebDev/assets/94478026/740b1faf-9899-41d2-93e8-6d284cea92ed)

**Comment by EmmaDawsonDev** [comment]
Reopening this since the navigation styling changes have not been merged yet.

**Comment by DIWAKARKASHYAP** [comment]
#322
