### ISSUE TITLE
Add TablesTemplate component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#33]
In the components/templates folder add a TablesTemplate.tsx file. Copy the structure of one of the other templates (they're all currently the same apart from name - contents will be added later). Update the component name so it matches the file name.

In the pages/[content].tsx file import the template and add it alphabetically in the correct place between the layout tags ```{page === "tables" && <Tables />}```

Add the template data to the config file in data/pages.tsx: ```{ name: "Tables", href: "/tables", content: "tables" }```

**Comment by Giriraj-Roy** [comment]
Hello ma'am,
I have gone through the repository and the given instructions. The issue seems to attract my interest and excites me to work on it. I humbly wait for you to assign the task to me if your analysis of my profile allows.

Yours Sincerely,
Giriraj Roy.

**Comment by adityabhattad2021** [comment]
Hey @EmmaDawsonDev , can I work on this one?

**Comment by saimaheshtaduri** [comment]
I am interested to work on this. can you assign to me? @EmmaDawsonDev

**Comment by EmmaDawsonDev** [comment]
Assigning to @saimaheshtaduri in order to share issues. If you’re taking part in hacktoberfest please feel free to wait until October 1st before making your pull request
