### ISSUE TITLE
CSS import inconsistencies

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#335]
I noticed that in some files the CSS modules are being imported as `style` and in others as `styles`. It would be good if they were all consistently imported as `styles`.

Task: Go through all components and check the CSS module import. Rename to `styles` if missing the s at the end. Then update all places where it is used in classNames.

**Comment by ujwalkumar1995** [comment]
Hey @EmmaDawsonDev 
I would like to work on this issue.
Could you please assign?

**Comment by EmmaDawsonDev** [comment]
Sure!
