### ISSUE TITLE
website link is not given in main repo 

### ISSUE THREAD

**Issue by DIWAKARKASHYAP** [AccessibleForAll/AccessibleWebDev#339]
![image](https://github.com/AccessibleForAll/AccessibleWebDev/assets/94478026/ae5e0379-e6a8-4f27-bb40-ef27e1bdc2c9)

**Comment by DIWAKARKASHYAP** [comment]
@EmmaDawsonDev please check

**Comment by EmmaDawsonDev** [comment]
This is because this repo is not going to be the main website for the Organization in the long run.
