### ISSUE TITLE
Add WorkInProgress component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#34]
In the components folder add a new folder called WorkInProgress and inside that add two files: WorkInProgress.tsx and WorkInProgress.module.css.

Inside the WorkInProgress.tsx file create a react component with the same name that is a section.

The section should include:

- a h2 with text - This section is a work in progress
- a p tag with text - Please come back at a later date. 
- a link to the github repo with text - Let us know what information you're looking for.

**Comment by Giriraj-Roy** [comment]
Hello ma'am,
I have gone through the repository and the given instructions. The issue seems to attract my interest and excites me to work on it. I humbly wait for you to assign the task to me if your analysis of my profile allows.

Yours Sincerely,
Giriraj Roy.

**Comment by EmmaDawsonDev** [comment]
Hi @Giriraj-Roy please feel free to work on this.

**Comment by EmmaDawsonDev** [comment]
> Hey @EmmaDawsonDev , I would love to do this task. Can you assign me please?😄

Unfortunately someone else asked first but please feel free to comment on another unassigned task.

**Comment by Giriraj-Roy** [comment]
Ma'am @EmmaDawsonDev thank you and I am excited to have got this issue assigned. Will start PRs once the hacktoberfest starts.

Thanking you,
Giriraj Roy
