### ISSUE TITLE
Footer links - "become a contributor" and "support us" are not opening in new tab/new window

### ISSUE THREAD

**Issue by SatyamSetia** [AccessibleForAll/AccessibleWebDev#341]
**Describe the bug**
Specifically 2 links in the footer - "Become a contributor" and "Support us" have open in new tab icon beside the text and aria-label="open in new window" as well but clicking these links opens the target url in same tab.

**To Reproduce**
Observe the links in app footer.
OR 
Try using a screen reader, it announces these link as "open in new window" but it gets open in same tab.

**Expected behaviour**
"Become a contributor" and "Support us" should open in new tab.

**Screenshots**

<img width="1784" alt="Screenshot 2023-07-08 at 12 47 31 PM" src="https://github.com/AccessibleForAll/AccessibleWebDev/assets/17885747/12342d9f-6ef2-4bc9-9515-cd9895f45b92">

**Comment by SatyamSetia** [comment]
Hey, @EmmaDawsonDev
Just wanted to share my interest on working this bug fix if in-case you find it to be a relevant issue to be fixed.

My proposal for the fix -
Using "target" attribute on these 2 anchor tags

**Comment by EmmaDawsonDev** [comment]
Hi Satyam, well spotted! These links are actually not meant to open in a new window, I must've missed asking the previous contributor to remove the icons. Please feel free to remove the icons.

**Comment by SatyamSetia** [comment]
Acknowledged 👍

**Comment by SatyamSetia** [comment]
Hey, @EmmaDawsonDev 
I have raised a PR for fixing this issue. Please find the changes here - https://github.com/AccessibleForAll/AccessibleWebDev/pull/342
Requesting your review whenever you get time.
