### ISSUE TITLE
Page Navigation links too close on mobile

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#348]
**Describe the bug**
In the page navigation component `NavPage` the links are too close together on mobile and therefore it's easy to press the wrong one. I have fairly small fingers yet my index finger covers three links at once.

Please increase the top and bottom margin to be 14 px each which should make it easier to press the correct link.

<img width="182" alt="image" src="https://github.com/AccessibleForAll/AccessibleWebDev/assets/57045550/94168210-5a07-4a32-85ec-3999f875975b">

**Comment by blyncnov** [comment]
Can I work on this ??

**Comment by blyncnov** [comment]
I'm already handling this 👌
