### ISSUE TITLE
Update website screenshot

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#349]
The design for the website has recently been updated. Replace the current websiteScreenshot.png with an updated version in the public/images folder. Make sure that the new image has the same name as the old one so that links do not need to be updated.

**Comment by DIWAKARKASHYAP** [comment]
i want to do this

**Comment by EmmaDawsonDev** [comment]
Sure :)

**Comment by DIWAKARKASHYAP** [comment]
PR #352

**Comment by DIWAKARKASHYAP** [comment]
@EmmaDawsonDev I have a question 
when ever we create pr , is i need to create an another branch ?

**Comment by EmmaDawsonDev** [comment]
> @EmmaDawsonDev I have a question when ever we create pr , is i need to create an another branch ?

Sorry, I missed this question. Yes, it's always best to create a new branch. Otherwise your main branch can get lots of merge conflicts and it becomes a headache to sort out every time.
