### ISSUE TITLE
Maintainer image load size can be reduced

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [AccessibleForAll/AccessibleWebDev#354]
**Is your feature request related to a problem? Please describe.**
The maintainer's Image is loaded at the default size **460 x 460** which is not required and is causing a high image load size. Hence, it will take longer time to load the website on devices with a poor network connection.

**Describe the solution you'd like**
The maintainer's image should be loaded at the size of the container by appending **&s=[size of the image required]** to the GitHub avatar URL.

**Additional context**
For @EmmaDawsonDev's GitHub **120 x 120** profile picture, the link will be [**`https://avatars.githubusercontent.com/u/57045550?v=4&s=120`**](https://avatars.githubusercontent.com/u/57045550?v=4&s=120).
For @ctoffanin's GitHub **120 x 120** profile picture, the link will be [**`https://avatars.githubusercontent.com/u/1682188?v=4&s=120`**](https://avatars.githubusercontent.com/u/1682188?v=4&s=120)

**This will reduce the image load size by about 90%. Reference : https://github.com/nyancodeid/quotes/issues/71#issue-1015935234**

**Comment by SaptarshiSarkar12** [comment]
If the issue looks good, can I work on this?

**Comment by EmmaDawsonDev** [comment]
Sure! Thanks for spotting it!

**Comment by SaptarshiSarkar12** [comment]
> Sure! Thanks for spotting it!

Thank you @EmmaDawsonDev !

**Comment by SaptarshiSarkar12** [comment]
@EmmaDawsonDev I have created a PR #355, please review it.
