### ISSUE TITLE
Do page on Audio 

### ISSUE THREAD

**Issue by CBID2** [AccessibleForAll/AccessibleWebDev#358]
**Is your feature request related to a problem? Please describe.**
I noticed that the [Audio page](https://accessibleweb.dev/audio) is not finished yet. 

**Describe the solution you'd like**
I'm doing 100 Days of Open Source, so I'd like to help create the content on this topic and use my PR as a highlight @EmmaDawsonDev. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by EmmaDawsonDev** [comment]
Sure, that would be great! 

Let me know if you want to discuss ideas for the different sections to write about.

**Comment by CBID2** [comment]
> Sure, that would be great! 
> 
> Let me know if you want to discuss ideas for the different sections to write about.

Adding closed captions would be a great way to start

**Comment by EmmaDawsonDev** [comment]
> > Sure, that would be great!
> > Let me know if you want to discuss ideas for the different sections to write about.
> 
> I can do a section on adding closed captions

That'd be a great start, thanks :)

**Comment by CBID2** [comment]
> > > Sure, that would be great!
> > > Let me know if you want to discuss ideas for the different sections to write about.
> > 
> > 
> > I can do a section on adding closed captions
> 
> That'd be a great start, thanks :)

Hi @EmmaDawsonDev! :) I setup the code component for the audio via PR #359, so you can start that part if you want(hence why the PR is in draft mode). From there, I can add the content about adding captions. How does that sound?

**Comment by EmmaDawsonDev** [comment]
Ok cool. I'm just off to bed as it's almost midnight here and I'm currently working on the navigation section which will hopefully be ready to push tomorrow. Then I can add the bits like the page navigation to the audio page. But feel free to add the closed captions content to a templateSection inside the audio page whenever you're ready.

**Comment by CBID2** [comment]
> Ok cool. I'm just off to bed as it's almost midnight here and I'm currently working on the navigation section which will hopefully be ready to push tomorrow. Then I can add the bits like the page navigation to the audio page. But feel free to add the closed captions content to a templateSection inside the audio page whenever you're ready. 

Will do @EmmaDawsonDev. Have a goodnight
