### ISSUE TITLE
Add HeadingsTemplate component

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#36]
In the components/templates folder add a HeadingsTemplate.tsx file. Copy the structure of one of the other templates (they're all currently the same apart from name - contents will be added later). Update the component name so it matches the file name.

In the pages/[content].tsx file import the template and add it alphabetically in the correct place between the layout tags ```{page === "headings" && <Headings />}```

Add the template data to the config file in data/pages.tsx: ```{ name: "Headings", href: "/headings", content: "headings" }```

**Comment by Giriraj-Roy** [comment]
Hello ma'am,
I have gone through the repository and the given instructions. The issue seems to attract my interest and excites me to work on it. I humbly wait for you to assign the task to me if your analysis of my profile allows.

Yours Sincerely,
Giriraj Roy.

**Comment by adityabhattad2021** [comment]
Hey @EmmaDawsonDev would love to do this task. Can you assign me please?😄

**Comment by kartikver15gr8** [comment]
@EmmaDawsonDev 
Hey Emma I've committed changes to this issue as u mentioned, please check them and let me know if you can merge them into the main branch.

😊😊

**Comment by ahmedsilat44** [comment]
Hello @EmmaDawsonDev . I  am a first time contributor and would like to do this task. Could you assign it to me ?

**Comment by EmmaDawsonDev** [comment]
@kartikver15gr8 is assigned to this one (they asked elsewhere) but feel free to comment on another issue

**Comment by kartikver15gr8** [comment]
Hey @EmmaDawsonDev shall I reopen my PRs

**Comment by kartikver15gr8** [comment]
Okay so should I delete this branch and then start fresh one.
Right??

**Comment by kartikver15gr8** [comment]
Hey @EmmaDawsonDev I've made pull requests for this issues. Kindly check them and merge them too😎😊😁😀
