### ISSUE TITLE
Need scroll margin or padding

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#365]
**Describe the bug**
When a user uses the page navigation links to navigate to a section of the page the heading ends up hidden underneath the fixed header. If I remember correctly it is possible to add something like scroll-margin-top as a css property and set it to the height of the header (a css variable) in order to push the scroll position down and prevent the heading from being hidden.

**To Reproduce**
1. Go to navigation page
2. Click on one of the links in the page navigation accordion
3. Notice that section heading is not visible

**Expected behavior**
Section heading is visible below the header

**Comment by 2div** [comment]
Hello , i would like to try to work on this bug and try to fix it.

**Comment by EmmaDawsonDev** [comment]
Sure! Have a go and just let me know if you need any help

**Comment by 2div** [comment]
Hi can you please my PR?
