### ISSUE TITLE
Add punctuation

### ISSUE THREAD

**Issue by itolimaesther** [AccessibleForAll/AccessibleWebDev#367]
I would like to correct a sentence in the Button tab. Do you mind assigning this to me @EmmaDawsonDev ?

**Comment by EmmaDawsonDev** [comment]
Sure, can you let me know which sentence is wrong?

**Comment by itolimaesther** [comment]
@EmmaDawsonDev please pardon me. I just need to add a punctuation in this sentence "An empty alt attribute has the most wide-spread support so that should be your go-to choice when using icons."

So I will be changing to this "An empty alt attribute has the most wide-spread support, so that should be your go-to choice when using icons." for better readability.

**Comment by EmmaDawsonDev** [comment]
Great! I assigned you 😊
