### ISSUE TITLE
Content for Link

### ISSUE THREAD

**Issue by itolimaesther** [AccessibleForAll/AccessibleWebDev#368]
There is no content for Link yet and I would like to add the content. Please assign this to me @EmmaDawsonDev

**Comment by EmmaDawsonDev** [comment]
Sure, please let me know if you need any help.

**Comment by CBID2** [comment]
Hey @EmmaDawsonDev. It’s been a while since this issue was assigned. Can I work on it?

**Comment by EmmaDawsonDev** [comment]
There's a pull request for it already, but you're welcome to take a look and leave comments or find another empty page and make a start

**Comment by CBID2** [comment]
> There's a pull request for it already, but you're welcome to take a look and leave comments or find another empty page and make a start 

Just made this issue: https://accessibleweb.dev/charts
