### ISSUE TITLE
[Feature] Open Graph 

### ISSUE THREAD

**Issue by Nakamcode** [AccessibleForAll/AccessibleWebDev#37]
**Is your feature request related to a problem? Please describe.**
A link without open graph tags reduces the click rate.

**Describe the solution you'd like**
Add Open Graph meta tags, Open Graphs meta tags help users optimize their social media link previews, so users always see the essential information. 

**Additional context**

![c5ae0478c1d04eb7fdb2f4df71895e89](https://user-images.githubusercontent.com/89482825/192184212-af7c40c0-dffa-4797-b48a-a39b5acda2e8.jpg)

**Comment by EmmaDawsonDev** [comment]
What does this do exactly? Can you explain a little bit more about it and what the benefits might be. I’m not keen on overloading the project with lots of packages unless I know they’ll be useful

**Comment by Nakamcode** [comment]
Open graph is an image that shows up when you share a link on social media, open graph comes with short description and a picture. This give more information about the link or url. Also open graph increases the click rate of a link. 

Here's a quick blog on it 

[Open Graph Meta Tags: Everything You Need to Know](https://ahrefs.com/blog/open-graph-meta-tags/#:~:text=Open%20Graph%20meta%20tags%20are%20snippets%20of%20code%20that%20control,head>%20section%20of%20a%20webpage.)

**Comment by EmmaDawsonDev** [comment]
I don't think this is needed right now but thank you for the suggestion.
