### ISSUE TITLE
dangling link at online website

### ISSUE THREAD

**Issue by Huluvu424242** [AccessibleForAll/AccessibleWebDev#371]
**Describe the bug**
The link in the hint of the day goes wrong to 404. 
![image](https://github.com/AccessibleForAll/AccessibleWebDev/assets/1297475/7410fbc6-6852-4579-8fec-2bbe7a3c6bf2)
at site: https://accessibleweb.dev/

The link https://www.w3.org/WAI/WCAG21/Techniques/semantic-structure.html does not exist.

**To Reproduce**
1. Go to https://accessibleweb.dev/
2. Click on f5 until hint of day is 'Use Semantic HTML'
3. Click at the link at 'Read more about semantic HTML...'
4. See error 404

**Expected behavior**
expecting context but unknow which content

Maybe:

* https://www.w3.org/WAI/WCAG21/Techniques/general/G115
* or https://webaim.org/techniques/semanticstructure/

**Comment by EmmaDawsonDev** [comment]
Thanks for finding this! Maybe we can change it to the webaim link you suggested. Do you want to be assigned?

**Comment by DIWAKARKASHYAP** [comment]
@EmmaDawsonDev i can do this

**Comment by EmmaDawsonDev** [comment]
Great!
