### ISSUE TITLE
Add Links Template Components

### ISSUE THREAD

**Issue by tashasyarifah** [AccessibleForAll/AccessibleWebDev#41]
Hi Emma, I notice you haven't added the links template component. I would like to work on that.

**Comment by EmmaDawsonDev** [comment]
Hi @tashasyarifah a links component already exists.

**Comment by EmmaDawsonDev** [comment]
I will hopefully be adding more issues at the weekend once Ive had a chance to see what’s missing so keep an eye out or if you notice something feel free to raise a new issue.

**Comment by tashasyarifah** [comment]
Okay, I'll wait for that! Thank you :)
