### ISSUE TITLE
Add a PR template

### ISSUE THREAD

**Issue by Pradumnasaraf** [AccessibleForAll/AccessibleWebDev#42]
Link to the official [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

**Comment by MrKrishnaAgarwal** [comment]
I can add a PR template, May I work on this @EmmaDawsonDev ?

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead!

**Comment by MrKrishnaAgarwal** [comment]
Thanks :+1:
