### ISSUE TITLE
Bug: a missing comma (,) in file pages.ts is throwing an error

### ISSUE THREAD

**Issue by ctoffanin** [AccessibleForAll/AccessibleWebDev#57]
**Describe the bug**
A missing `,` in the file `pages.ts` throws an error

**To Reproduce**
1. Run `yarn dev`
2. Go to `http://localhost:3000/`
3. See the error

**Expected behavior**
It's expected to see the home page.

**Screenshots**
![Screenshot 2022-10-01 at 11 29 14](https://user-images.githubusercontent.com/1682188/193402818-a0dacf5e-bb2d-410a-a07f-46aff1f642d1.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome, Safari, firefox

**Additional context**
I believe it was introduced in PR #54

**Comment by EmmaDawsonDev** [comment]
You are correct, I obviously was too quick in merging all the PRs. Problem is on line 13 of data/pages. Did you want to fix it and get another PR?

**Comment by ctoffanin** [comment]
I have the same problem sometimes :)
Yes, you can assign it to me. I'm going to fix it straight away.
