### ISSUE TITLE
Add sentence about gitpod to readme.

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#62]
Between the gitpod heading and the gitpod button add the following sentence to explain what Gitpod is:

Gitpod allows you to view and interact with this code directly in the browser without the need to clone it to your local machine. If you wish to make changes that lead to a pull request, remember to fork the repository then click the Gitpod button in the forked readme. Otherwise, feel free to play around with the code by clicking here.

**Comment by EmmaDawsonDev** [comment]
@yashdev9274

**Comment by Viki-07** [comment]
Hey @EmmaDawsonDev, It seems interesting and I would like to work on this and It will be very helpful for me as I am participating in Hacktoberfest. Kindly assign me for the above

**Comment by EmmaDawsonDev** [comment]
Hi @Viki-07 this one is already assigned to yash but I have the same issue on another repo if you want to comment there I will assign you https://github.com/AccessibleForAll/ColorPaletteCombos/issues/29

**Comment by MrKrishnaAgarwal** [comment]
@EmmaDawsonDev Please review my PR #60

**Comment by yashdev9274** [comment]
Hey @EmmaDawsonDev, can I work on it?

**Comment by yashdev9274** [comment]
> Hi @Viki-07 this one is already assigned to yash but I have the same issue on another repo if you want to comment there I will assign you [AccessibleForAll/ColorPaletteCombos#29](https://github.com/AccessibleForAll/ColorPaletteCombos/issues/29)

Thank you @EmmaDawsonDev  , I'll work on this one.

**Comment by yashdev9274** [comment]
![image](https://user-images.githubusercontent.com/72986960/193457316-e7d20d47-69de-44f7-a955-a5a173ac3e6e.png)


Hey @EmmaDawsonDev I made this changes, please take a look and let me know about your thoughts.

**Comment by EmmaDawsonDev** [comment]
Can you make a pull request to this repository instead of to the fork?

**Comment by yashdev9274** [comment]
yes did change it.

**Comment by yashdev9274** [comment]
![image](https://user-images.githubusercontent.com/72986960/193463425-2fd335e9-017c-4523-ad81-1822d526089c.png)

Here I did the changes

**Comment by EmmaDawsonDev** [comment]
@yashdev9274 How's it going on this one?

**Comment by yashdev9274** [comment]
I'll update it tonight.

**Comment by EmmaDawsonDev** [comment]
No rush, just wanted to know how it’s going
