### ISSUE TITLE
Update .gitpod.yml file

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#71]
**Describe the bug**
On line 5 in the ```.gitpod.yml``` file it says ```yarn run start``` when it should say ```yarn dev```

**Comment by slayeh17** [comment]
I would like to work on this😊

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead :)

**Comment by ShorunTech** [comment]
Weldone @EmmaDawsonDev for helping others.
