### ISSUE TITLE
Change font family of paragraph text.

### ISSUE THREAD

**Issue by Susmita-Dey** [AccessibleForAll/AccessibleWebDev#78]
**Is your feature request related to a problem? Please describe.**
This is a new feature.

**Describe the solution you'd like**
I would like to change the font family of paragrah text to either [Inconsolata](https://fonts.google.com/specimen/Inconsolata) or to [Roboto](https://fonts.google.com/specimen/Roboto) in order to differentiate it from the header and sidebar. 

**Describe alternatives you've considered**
No alternatives. You can help me to choose any one of the above fonts which looks good to you.

**Additional context**
This is under hacktoberfest contribution. Kindly assign it to me.

**Comment by EmmaDawsonDev** [comment]
I'm quite happy with the current font choice at the moment but thanks for raising the discussion. I'll be adding a few more issues for hacktoberfest in a few days so feel free to keep an eye out for those but just now I'm sick so I'm taking some rest.
