### ISSUE TITLE
Import WIP component to Animation template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#93]
Please import the WorkInProgress component into the AnimationTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by alberturria** [comment]
Hi @EmmaDawsonDev may I work on this issue? 🙂

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead :)
