### ISSUE TITLE
Import WIP component into AudioTemplate

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#94]
Please import the WorkInProgress component into the AudioTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by jyotika6221** [comment]
hey, if the issue is still open, i can fix it. please assign it to me.

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead @jyotika6221

**Comment by jyotika6221** [comment]
ok.

**Comment by jyotika6221** [comment]
Can you please elaborate how to work on this issue? I'm facing difficulty.

**Comment by EmmaDawsonDev** [comment]
Sure. How far have you gotten?

**Comment by jyotika6221** [comment]
I forked and cloned the repository , went through the AlertTemplates component to see how is it done and saw the code.
But kindly tell me which file do i need to add this code to? Or if something else needs to be done please explain. 
Thank you.

**Comment by EmmaDawsonDev** [comment]
If you look in the folder Components/ContentTemplates you will find a file called AudioTemplate.

It currently looks like this 
```
import React from "react"

const AudioTemplate = () => {
	return <div>AudioTemplate</div>
}

export default AudioTemplate
```

Update it so it looks like this instead: 
```
import React from "react"
import WorkInProgress from "../WorkInProgress/WorkInProgress"

const AudioTemplate = () => {
	return <WorkInProgress />
}

export default AudioTemplate
```

**Comment by jyotika6221** [comment]
Thank you, i have requested for the pr.
