### ISSUE TITLE
Import WIP to captchas template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#95]
Please import the WorkInProgress component into the CaptchasTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by stevenovak123** [comment]
Hey, Could I work on this?

**Comment by EmmaDawsonDev** [comment]
Sure! Go ahead :)
