### ISSUE TITLE
Import WIP to charts template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#96]
Please import the WorkInProgress component into the ChartsTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by PeroHub** [comment]
> Please import the WorkInProgress component into the ChartsTemplate found inside components/ContentTemplates folder.
> 
> Then render the WorkInProgress component instead of the current div and placeholder sentence.
> 
> See the AlertsTemplate component if unsure how to do this and follow the same pattern.

@EmmaDawsonDev please assign me this issue

**Comment by ctoffanin** [comment]
Yes, sure!

**Comment by PeroHub** [comment]
> Please import the WorkInProgress component into the ChartsTemplate found inside components/ContentTemplates folder.
> 
> Then render the WorkInProgress component instead of the current div and placeholder sentence.
> 
> See the AlertsTemplate component if unsure how to do this and follow the same pattern.

@EmmaDawsonDev please assign me this issue

**Comment by ctoffanin** [comment]
> @EmmaDawsonDev please assign me this issue

It's assigned to you.

**Comment by PeroHub** [comment]
> 
Oh thank you

**Comment by PeroHub** [comment]
> 
Oh thank you
