### ISSUE TITLE
Import WIP into breadcrumbs template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#97]
Please import the WorkInProgress component into the BreadcrumbsTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by Heismanish** [comment]
Hey @EmmaDawsonDev, I would like to work on this issue.

**Comment by ctoffanin** [comment]
Hey, yes, go ahead!

**Comment by Heismanish** [comment]
Hey @ctoffanin, made a PR for this issue.
