### ISSUE TITLE
import WIP to buttons template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#98]
Please import the WorkInProgress component into the ButtonsTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by rafaeldias97** [comment]
I would like to work on this.

**Comment by ctoffanin** [comment]
Sure, go ahead :)
