### ISSUE TITLE
import WIP to form template

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/AccessibleWebDev#99]
Please import the WorkInProgress component into the FormTemplate found inside components/ContentTemplates folder.

Then render the WorkInProgress component instead of the current div and placeholder sentence.

See the AlertsTemplate component if unsure how to do this and follow the same pattern.

**Comment by HondaChan14** [comment]
Hello I could I be assigned this :)

**Comment by ctoffanin** [comment]
Yes, sure, go ahead!
